### ISSUE TITLE
Unable to run first "Configuring Generators" example. Getting rather frustrated...

### ISSUE THREAD

**Issue by Muzietto** [pholser/junit-quickcheck#104]
I accept the working hypothesis that I may not be the smartest property-based tester on the block, but getting to run any example from the official JUnit-Quickcheck documentation seems to me a hugely difficult undertaking.

Let's take now the [example about `@Positive` integers](http://pholser.github.io/junit-quickcheck/site/0.6/usage/configuring.html).

First observation: the generator's classname ought to be `PositiveGenerator` rather than `IntegralGenerator`, but I guess this was just a typo.

I try to give some meaning to the test method `Numbers.holds` by putting inside [the assertion that `i` should be, well ...positive](https://github.com/Muzietto/quick-java-check/blob/master/src/test/java/net/faustinelli/quickcheck/positive/Numbers.java#L24).

Well, it comes out that this ain't true, because the thesis is immediately falsified by shrinking to `[0]` the value.

Let's then [inhibit shrinking](https://github.com/Muzietto/quick-java-check/blob/master/src/test/java/net/faustinelli/quickcheck/positive/Numbers.java#L22), but that does not help either. The property test fails and a breakpoint inside the test method shows that already the first value provided to `i` is negative, in spite of all the paraphernalia in place.

I wasn't able to make the property test pass, not even by putting the annotation `@From` to force usage of `PositiveGenerator.class` (which would've anyhow spoiled the whole example). Other breakpoints put inside `PositiveGenerator.configure` and `PositiveGenerator.generate` remain silent and show that the class is not used during the run, which makes me suspect that a plain generic Integer generator is chosen by JUnit-Quickcheck to provide the test method with the int's it needs.

__What am I not understanding? Can I see a really working example of this code? Shouldn't the official documentation be made out of actually running code?__

My code is [here](https://github.com/Muzietto/quick-java-check/tree/master/src/test/java/net/faustinelli/quickcheck/positive).

**Comment by pholser** [comment]
Similarly to #103, generator `PositiveGenerator` needs a `public` zero-arg constructor in order for junit-quickcheck to instantiate it:

    public class PositiveGenerator extends Generator<Integer> {
        public PositiveGenerator() {
            super(Integer.class, int.class);
        }
    }

I'm looking further into the issues you're describing and will advise as soon as I can.

**Comment by pholser** [comment]
Also, ensure that your configuration annotation `@Positive` is marked as `@Retention(RetentionPolicy.RUNTIME)`. Otherwise, junit-quickcheck will not be able to detect it.

**Comment by pholser** [comment]
A few more notes here:

* For a given property parameter `p`, junit-quickcheck must decide what generators can produce values for it.
* If `p` is marked as `@From`, then the generator(s) named there will be used.
* If `p` is not marked as `@From`, then junit-quickcheck will collect any generators that have been made available to a `ServiceLoader` in the usual way (META-INF/services/com.pholser.junit.quickcheck.generator.Generator file), that also honor all of the generator configuration annotations on `p`, and call upon one of them on each generation (with approximately equal probability).

**Comment by Muzietto** [comment]
I managed to make it run thanks to the `@From` annotation. Without that, I have tried a 5-6 runs and the `PositiveGenerator` is never used, either by chance or systematically.

This is [the code](https://github.com/Muzietto/quick-java-check/tree/master/src/test/java/net/faustinelli/quickcheck/positive)

This example of using the special annotation to indicate clearly the sort integer we want to have in the test method remains useful. However, the case for using such construction without `@From` seems very weak to me, as junit-quickheck (if I understand your words correctly) will see our generator just as one of the many available, whereas our intent is to have only our one used.

The fact that `@Retention` is mandatory imho should be emphasized in the doc. People like me, with little exposition to Java annotations, tend to limitate the noise while trying to understand.

If you feel this example can be made to run without the `@From`, with the `PositiveGenerator` chosen as sole source for `@Positive`'s please let me see where my code is improvable. Otherwise you're welcome to close this issue.

**Comment by pholser** [comment]
@Muzietto I've updated some of the docs -- latest snapshot is at http://pholser.github.io/junit-quickcheck/site/0.7-SNAPSHOT/ . I've incorporated some of your suggestions. Hopefully this makes for a clearer path to success when using junit-quickcheck.

**Comment by pholser** [comment]
@Muzietto Also, if you would, have a look at [IntProperties](https://github.com/pholser/junit-quickcheck-scratchpad/blob/master/src/test/java/com/pholser/junit/quickcheck/scratchpad/java/lang/IntProperties.java) in [junit-quickcheck-scratchpad](https://github.com/pholser/junit-quickcheck-scratchpad) -- an example of how to get a generator of `int` that can be configured with an annotation to be used without `@From`.

Hope this helps!

**Comment by Muzietto** [comment]
Great. I can't wait to have 0.7 available. I reckon the generator at [Configuring Generators](http://pholser.github.io/junit-quickcheck/site/0.7-SNAPSHOT/usage/configuring.html)  should be called `NonNegativeGenerator` instead of `IntegralGenerator`.
