### ISSUE TITLE
Expose assertion detail on failure

### ISSUE THREAD

**Issue by turnerjasonuk** [pholser/junit-quickcheck#116]
Just an improvement, not an issue.

When getting tests going or using in TDD it is pretty often the case that you don't need to run the reported failure case to find the root cause, but if the assertion were more fully reported could directly find . So it would be handy if the final shrunk failure could be reported with the full AssertionError message. I normally use Hamcrest or similar for assertions, so it then gives pretty indicative report.

**Comment by pholser** [comment]
@turnerjasonuk Thanks for your interest! Would you mind to try the latest 0.7 snapshot at oss.sonatype.org? I've enhanced the messaging in the `AssertionError`s junit-quickcheck emits. Let me know whether this suits your needs.

**Comment by pholser** [comment]
@turnerjasonuk See http://pholser.github.io/junit-quickcheck/site/0.7-SNAPSHOT/usage/seed.html for an example assertion message.

**Comment by turnerjasonuk** [comment]
Thanks will do

**Comment by turnerjasonuk** [comment]
Hi Paul,
Thanks - I tried 0.7, that was great. Very handy as I said when TDDing or adding test, as I know basically I am more likely to have made a simple error than found a deep bug, and can then quickly resolve.
Really appreciate the library - I have for many years used primitive property based testing by testing invariants but lacking strong generator support or shrinking etc, and then recently in Clojure used test.check - but my day job is Java so great to have a good library option.
My next plan time allowing is to add some generators - I would for example like a non-empty list generator rather than setting size (1,100) - so will probably bother you with some questions.
Best wishes, good weekend, and thanks,
Jason 

    On Monday, 27 June 2016, 21:41, Jason Turner <turnerjasonuk@yahoo.co.uk> wrote:
 

 Thanks will do

Sent from my iPhone
On 23 Jun 2016, at 17:54, Paul Holser <notifications@github.com> wrote:


@turnerjasonuk Thanks for your interest! Would you mind to try the latest 0.7 snapshot at oss.sonatype.org? I've enhanced the messaging in the AssertionErrors junit-quickcheck emits. Let me know whether this suits your needs.—

**Comment by pholser** [comment]
@turnerjasonuk Great! Thanks for the feedback. Feel free to mail me with questions, or join the Google group and post there.
