### ISSUE TITLE
Find replacement that unifies capability of javaRuntype and generics-resolver

### ISSUE THREAD

**Issue by pholser** [pholser/junit-quickcheck#118]
Candidates:

- Guava TypeToken
- Spring ResolvableType
- gentyref
- others??

When junit-quickcheck goes to invoke a property method, it needs to generate arguments for the method that satisfy the type constraints of the parameters of the method. A method parameter may have generics in it, possibly with wildcards and/or type variables. In the context of an instance of the test class, the type variables need to be resolved, and appropriate generator(s) chosen for the method parameter.

To solve this problem, currently junit-quickcheck leverages two separate libraries: one of which resolves type variables, and one of which wraps type instances in its own meta-model that allows us to ask for assignability, type parameters, etc. It would be great if we could unify these capabilities in one dependency.

**Comment by tinkerware** [comment]
I know of https://github.com/FasterXML/java-classmate to resolve generic types and their members; it may help.

**Comment by pholser** [comment]
So far, nothing seems to suit. I'll live with what we have for now.
