### ISSUE TITLE
No way to provide a Distribution to CharacterGenerator

### ISSUE THREAD

**Issue by david-lshift** [pholser/junit-quickcheck#119]

**Comment by david-lshift** [comment]
I've also found FixedValuesGenerator.

I'm guess it's not really intended that I can use generators in a way that's repeatable. That seems like a shame: I just want to save the seed I used to generate a failure.

**Comment by pholser** [comment]
@david-lshift Thanks for your interest! I'm not certain whether you're looking for a way to influence  the distribution on a random generation, or run a test using a fixed seed, or both.

For the latter: with 0.7-alpha-1 and beyond, when a counterexample is found, the assertion error message will contain the seed values used to generate each of the individual arguments for the property method that failed. You can verify the property again using those seeds by marking each of the property's parameters with `@When(seed = ...)`.

For the former: I'm certainly open to introducing different probability distributions to random generation in junit-quickcheck.

When you say `FixedValuesGenerator` -- are you referring to [this](https://quickcheck.java.net/nonav/javadoc/net/java/quickcheck/generator/support/FixedValuesGenerator.html)? I'm open to being able to do something like this. It sounds similar to #86 -- I haven't landed on a way to provide any generator a neat way of specifying the set of values. I'm open to suggestions, for certain.

**Comment by pholser** [comment]
@david-lshift Note that #125 will introduce an `@Only({value, ..., value})` annotation, where you can mark a property parameter with it and each verification of the property will choose a value from the specified set at random.

In the absence of any other feedback, I'm closing this issue.
