### ISSUE TITLE
javafx.util.Pair seems to break open-jdk support

### ISSUE THREAD

**Issue by philipp-classen** [pholser/junit-quickcheck#120]
javafx.util.Pair in Gen (https://github.com/pholser/junit-quickcheck/blob/master/core/src/main/java/com/pholser/junit/quickcheck/generator/Gen.java#L39)  requires that jfxrt.jar in in the classpath.

That seems to be the case for oracle-jdk-8 but not open-jdk-8. At least that is what I get on Linux.

Maybe it is a good idea to replace it by an own Pair implementation?

**Comment by philipp-classen** [comment]
I just saw this stackoverflow answer, which confirms that JavaFX is not part of OpenJDK:

http://stackoverflow.com/a/22516005/783510

**Comment by pholser** [comment]
@philipp-classen Bummer. I was hoping not to have to roll my own Pair. I will though.

**Comment by pholser** [comment]
@philipp-classen A resolution for this should be in the latest 0.7 snapshot (pushing now) at oss.sonatype.org -- I rolled my own Pair to replace the one from JavaFX. Sorry for the trouble.
