### ISSUE TITLE
Lambdas.makeLambda does not generate pure functions

### ISSUE THREAD

**Issue by jhinch** [pholser/junit-quickcheck#122]
This is due to the fact that `GenerationStatus.size()` can change between each invocation for the default implementation of `GenerationStatus`. This means that the `SourceOfRandomness` given to the `returnValueGenerator` is no the only source of randomness.

The easiest way to fix this would be to make an immutable copy of the `GenerationStatus` at construction time of the lambda

**Comment by pholser** [comment]
@jhinch Excellent point! I'll look at the PR this weekend.

**Comment by pholser** [comment]
Merged! This is in 0.6.1.

I had taken some care to ensure that the products of Lambdas are pure, but forgot that some return value generators might refer to `size()`, which carries an element of randomness.
