### ISSUE TITLE
Have PropertyFalsifier include the error message in the first line of the message

### ISSUE THREAD

**Issue by m0smith** [pholser/junit-quickcheck#127]
When the @Property is run by maven surefire, the result looks like:

>  Failed tests:   sortIntegers(org.ihc.train.pbt.SortTest): Property sortIntegers falsified via shrinking.

It will be nice if it included the error message as well before the first line break:

> Failed tests:   sortIntegers(org.ihc.train.pbt.SortTest): Property sortIntegers falsified via shrinking:Shrink failure message: [expected:<[1882, 0, 0, 0]> but was:<[0, 0, 0, 1882]>]

This would more closely match what junit does naturally.

**Comment by pholser** [comment]
@m0smith Thanks for your interest in junit-quickcheck!

What version are you using? In 0.7-alpha-2, running [ShrinkingCompletely](https://github.com/pholser/junit-quickcheck/blob/master/core/src/test/java/com/pholser/junit/quickcheck/ShrinkingTest.java) yields the results below. Would these suffice?

```
$ mvn -Dtest='ShrinkingTest$ShrinkingCompletely test
...
Failed tests: 
  ShrinkingTest$ShrinkingCompletely.shouldHold:56 Property shouldHold falsified via shrinking.
Shrink failure message: [
Expected: a value less than <1>
     but: <1> was equal to <1>]
Shrunken args: [Foo[1]]
Original failure message: [
Expected: a value less than <1>
     but: <1504480407> was greater than <1>]
Original args: [Foo[1504480407]]
Seeds: [-8844967027337711751]
```

**Comment by m0smith** [comment]
The only thing to change would be to remove the first \n so the error generated "Expected ... but was ..." would show in the maven surefire summary line.  Otherwise I have to go hunt for it in the output file.

**Comment by pholser** [comment]
@m0smith That'd be great. Looking forward to your PR.

**Comment by pholser** [comment]
@m0smith Thanks for the PR! Hope this helps.

**Comment by m0smith** [comment]
Many thanks for this and the whole project.  I will anxiously wait for it to hit the maven repos
