### ISSUE TITLE
quickcheck breaks mvn test when using maven-compiler-plugin

### ISSUE THREAD

**Issue by amc6** [pholser/junit-quickcheck#133]
Using quickcheck as a maven dependency seems to break when its used along side the maven-compiler-plugin. I've attached a small sample project that should illustrate the problem. If you run `mvn test` you'll see that the test compilation fails. If you comment out either the maven-compiler-plugin or the quickcheck depedency (which isn't actually used by any of the code in this sample project) then `mvn test` will succeed. 

If you change the scope of the quickcheck dependency to compile instead of test, it will also cause `mvn compile` to fail.

If you remove `<arg>-Werror</arg>` from the plugin, `mvn test` will again succeed. But `-Werror` is a useful feature that I would like to keep using.

Its possible this is a bug with maven-compiler-plugin, but I haven't seen anything like this with the other dependencies we are using. I'm hoping you'll have some idea what might be going on here.

Thanks!

[test.zip](https://github.com/pholser/junit-quickcheck/files/501918/test.zip)

**Comment by amc6** [comment]
Here is the maven output as well.
[log.txt](https://github.com/pholser/junit-quickcheck/files/501933/log.txt)

**Comment by pholser** [comment]
@amc6 I've looked at the Maven log you posted -- it looks as though your project depends on [this rendition of QuickCheck in Java](https://bitbucket.org/blob79/quickcheck) rather than junit-quickcheck.

**Comment by amc6** [comment]
Ah my bad. I was debugging this in someone else's code, so I didn't realize that it was a different library. Bad Google-fu. Thanks for the help!
