### ISSUE TITLE
Generation of edge cases

### ISSUE THREAD

**Issue by akafred** [pholser/junit-quickcheck#140]
Have you considered generators more likely to generate edge cases?

Examples of edge cases for integral types the minimal value, `-1`, `0`, `1`, the maximal value; for Strings `null`, `""`, `" "` and in general for object types `null`. I suggest generator writers will have a good idea of what the edge cases are.

I understand that this will mean the uniform randomness used today will be "broken". But it could perhaps help reduce the number of tests needed and catch more bugs?

One possible way to do this would be to include an `@EdgeCases` annotation which generators can act on.

Another idea would be to add an `@Also` annotation. This could be like to `@Only`, but including cases that generators choose more often.

**Comment by pholser** [comment]
@akafred Thanks for your interest in junit-quickcheck!

I'm certainly open to this. In the interim, you can add such generators to the mix yourself, e.g.:

    public class Edgy extends Generator<Integer> {
        public EdgyIntegerGenerator() {
            super(asList(Integer.class, int.class));
        }

        @Override public Integer generate(SourceOfRandomness r, GenerationStatus s) {
            return r.choose(asList(-1, 0, 1, Integer.MAX_VALUE, Integer.MIN_VALUE);
        }
    }

    public class IntegerProperties {
        @Property public void edgy(@From(Edgy.class) int i) {
            // ...
        }
    }

**Comment by akafred** [comment]
Yep - already doing that (generator that generates edge cases + random) - but it is a bit of extra effort :-)

**Comment by pholser** [comment]
Agreed, more effort than I'd like. Will consider approaches.

**Comment by m0smith** [comment]
Other implementations seem to use the "edge cases" when the size (as applied to shrinking) is 0 or its smallest value. The randomness is constrained by the current size.   The smallest string is naturally null or the empty string.  The smallest number (int, long, char) is 0 and spreads out from there in both directions as the size increases.  Making MAX_INTEGER and MIN_INTEGER to also be considered small would be the tricky part.

**Comment by Baasie** [comment]
Hi,

I have been working more or less now 3 months with your framework, and I really enjoy using it.
I have started to blog and talk about your framework and property based testing.
And one thing that came up recently was exactly this, while running a property with minInt = 21 it seem to only generate numbers in the 200000 around. Random as expected, but like the issues described maybe it is nice to generate edge case more.

If you need any help please tell me and i might be able to join in :).

Cheers!

**Comment by pholser** [comment]
@Baasie I'm considering addressing generation of "edge cases" via #125 -- I figure this will allow test writers to say "these cases are important" or "these cases are the only ones I wish to consider".

I am considering splitting that issue. The part that allows either "sampling" or "exhaustive" mode is basically done, and I kind of don't want to hold it up while the `@Only/@Also` stuff is under development (whenever I can get to it).

**Comment by Baasie** [comment]
Hi @pholser , thank you for the reply and the hard work! The samling and exhaustive mode sounds already a perfect upgrade to use :+1: 

I will follow the issue and look out once you will merge it.

If there is any help you need, just ask!

**Comment by pholser** [comment]
With #125 and #164 in the can, I'm closing this if there are no objections.
