### ISSUE TITLE
Support Java 7

### ISSUE THREAD

**Issue by wbazant** [pholser/junit-quickcheck#141]
I wanted to try using this library in [Expression Atlas](www.github.com/gxa/atlas). We are still on Java 7, sadly, because we're relying on some infrastructure that is built around Java 7.

I tried bringing in the dependencies, installing via Maven, and running the example test, but I see this:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/pholser/junit/quickcheck/runner/JUnitQuickcheck : Unsupported major.minor version 52.0

Internet tells me this means sadness - the classes in the jar are built with Java 8 so won't run.

Is it possible to cross compile the project so that it supports Java 7?

**Comment by pholser** [comment]
@wbazant Thanks for your interest!

Sadly, at this point attempting to back-compile or support running junit-quickcheck on JDK < 8 looks like a massive effort. I feel like there's enough benefit to the features afforded by JDK >= 8 to warrant abandoning JDK <= 7.

**Comment by wbazant** [comment]
@pholser 
Thanks for replying! I didn't try building you from source, so I don't know if it's feasible. If it's the case that you used some Java 8 specific features in the code and the cost of supporting a (officially, EOL ) version of JDK is nontrivial, I agree with the judgement that it's not worth it.

We'll upgrade, then we'll be back! =)
