### ISSUE TITLE
Exception on using @From(Ctor.class) or @From(Fields.class) in contract test

### ISSUE THREAD

**Issue by bheisler** [pholser/junit-quickcheck#143]
This code:

    public class MinimalExample {
    
        public static class TestObject {
            private final String str;
    
            public TestObject( String str ) {
                this.str = str;
            }
        }
    
        public interface ContractTest<T> {
            @Property
            public default void testProperty( @From( Ctor.class ) T value ) {
                assertEquals( value, value );
            }
        }
    
        @RunWith( JUnitQuickcheck.class )
        public static class TestObjectTests implements ContractTest<TestObject> {
        }
    }

Produces this exception:

>     java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.Class
>     at com.pholser.junit.quickcheck.internal.ParameterTypeContext.rawParameterType(ParameterTypeContext.java:175)
>     at com.pholser.junit.quickcheck.internal.ParameterTypeContext.makeGenerator(ParameterTypeContext.java:167)
>     at com.pholser.junit.quickcheck.internal.ParameterTypeContext.addGenerators(ParameterTypeContext.java:156)
>     at com.pholser.junit.quickcheck.internal.ParameterTypeContext.annotate(ParameterTypeContext.java:141)
>     at com.pholser.junit.quickcheck.internal.PropertyParameterContext.annotate(PropertyParameterContext.java:54)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.parameterContextFor(PropertyStatement.java:190)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$parameters$39(PropertyStatement.java:167)
>     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>     at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
>     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.parameters(PropertyStatement.java:174)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:89)
>     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>     at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
>     at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

I wasn't sure if that was the intended syntax, but it sill fails if I move the `@From` to the test class' type parameter like so:

    public interface ContractTest<T> {
        @Property
        public default void testProperty( T value ) {
            assertEquals( value, value );
        }
    }

    @RunWith( JUnitQuickcheck.class )
    public static class TestObjectTests implements ContractTest<@From( Ctor.class ) TestObject> {
    }

This fails with this exception:

>     java.lang.IllegalArgumentException: Cannot find generator for com.sedsystems.codegen.java.tests.namedtypes.MinimalExample$ArgContractTest.testProperty:arg0 of type T
>     at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.matchingGenerators(GeneratorRepository.java:253)
>     at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.generatorFor(GeneratorRepository.java:234)
>     at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.produceGenerator(GeneratorRepository.java:216)
>     at com.pholser.junit.quickcheck.internal.generator.PropertyParameterGenerationContext.<init>(PropertyParameterGenerationContext.java:58)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$parameters$40(PropertyStatement.java:168)
>     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>     at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
>     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
>     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.parameters(PropertyStatement.java:174)
>     at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:89)
>     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>     at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
>     at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
>     at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

This occurs on both 0.8-alpha-1 and 0.8-alpha-2.

**Comment by pholser** [comment]
Seems like I need to decide whether `@From` gets to play in this context. Thanks for the feedback.

**Comment by pholser** [comment]
junit-quickcheck wants to scrape annotations off of method parameters, not from uses of types in an `implements` clause. I think the right place for `@From(Ctor.class)` in this context should be on the parameter of type `T` in the contract test. This reads to me as "this property holds true for any type that can be instantiated using a single accessible constructor".

I think I can make this work by substituting the resolution of type variable `T`. On its way.

**Comment by pholser** [comment]
@bheisler Have a look, if you would, at the PR above -- looks like this will resolve this issue. If you're OK with it, this will show up in 0.8 alpha 4. Thanks for the feedback!

**Comment by pholser** [comment]
@bheisler I'm going to merge in the PR. This will show up in 0.8 alpha 4.
