### ISSUE TITLE
Exception on using arrays in contract test

### ISSUE THREAD

**Issue by bheisler** [pholser/junit-quickcheck#144]
This code:

    public class MinimalExample {
    
        interface ContractTest<T> {
            @Property
            default void testProperty( T value ) {
                assert value == value;
            }
        }
    
        @RunWith( JUnitQuickcheck.class )
        public static class ArrayTest implements ContractTest<byte[]> {
    
        }
    }

Produces this exception:

> java.lang.ClassCastException: sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeVariableImpl cannot be cast to java.lang.reflect.AnnotatedArrayType
> 	at com.pholser.junit.quickcheck.internal.ParameterTypeContext.arrayComponentContext(ParameterTypeContext.java:243)
> 	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.generatorForArrayType(GeneratorRepository.java:238)
> 	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.generatorFor(GeneratorRepository.java:230)
> 	at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.produceGenerator(GeneratorRepository.java:216)
> 	at com.pholser.junit.quickcheck.internal.generator.PropertyParameterGenerationContext.<init>(PropertyParameterGenerationContext.java:58)
> 	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$parameters$40(PropertyStatement.java:168)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at com.pholser.junit.quickcheck.runner.PropertyStatement.parameters(PropertyStatement.java:174)
> 	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:89)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

This occurs on 0.8-alpha1 and 0.8-alpha-2.

**Comment by pholser** [comment]
It would appear there's some work to do re: resolving type variables in methods. Thanks for the feedback.

**Comment by pholser** [comment]
@Redattack34 Yeah...this and #143 are going to be tricky.

At the point where we're wanting to make a generator for the parameter of `testProperty`, we know that `T` resolves to `byte[]`. But it's assuming that the parameter of `testProperty` is a thing of type `AnnotatedArrayType`, and it's not -- it's still really `T` (an `AnnotatedTypeVariable`). it'd be great if resolving `T` resolved it to a thing that preserved annotations on the thing being plugged in.

**Comment by pholser** [comment]
@bheisler Please have a look at the PR above -- I've got your test case passing. Over time, we'll have to decide how, if at all, to handle markings on type parameters in contract tests and their "instantiations" in subclasses.

**Comment by bheisler** [comment]
This fix works for me. Thanks for the quick response.

**Comment by pholser** [comment]
Fix is in 0.8 alpha 3. Hope this helps. Thanks!
