### ISSUE TITLE
API Ergonimics

### ISSUE THREAD

**Issue by mspiegel** [pholser/junit-quickcheck#150]
Hi!

I'm very excited about using junit-quickcheck it is the most active GitHub project for Java-based property testing. I plan on using it as a part of a JSON specification language I am working on: https://github.com/json-structure/json-structure. The idea is to use a specification (similar to JSON schema but simpler for statically-typed languages) to generate arbitrary JSON values.

Most of the functionality I need is present in junit-quickcheck. I've noticed in several instances where the API is designed for use as Java annotations and it is awkward when used as an API. I'm happy to submit pull requests for these features. Before I do that I want to see if there is something I have not considered. Or if these features are out of scope.

- min and max properties for StringGenerator for bounds on the length of the string.
- In CollectionGenerator#size() using the status.size() hint when sizeField is non-null. Currently there is no way to specify only a minimum size. So if I want at least five elements then I must generate anywhere between 5 and 2^31 elements. This is relatively small patch I can volunteer to do it.
- How to combine edge cases with a generator? This request is basically #140. It would be nice to have a generator that tries all the edge cases first. After those have been exhausted then switch to another provided generator. I can sort-of implement this but I'm not sure how to do the shrinking correctly.

**Comment by mspiegel** [comment]
Hmm. On the second feature "using the status.size() hint when sizeField is non-null" I can see now how that might be the opposite behavior from what someone intended. ie. if they want the range (0, 1,000,000) then they don't want to wait a million generations to test the large sizes. Maybe add to CollectionGenerator a new field that is a lambda that accepts (SourceOfRandomness, GenerationStatus) and returns an integer that indicates the next size? Not sure how to expose that functionality through a Java Annotation.

**Comment by pholser** [comment]
@mspiegel re: min/max length markings on `String` parameters -- admitting the existing `@Size` shouldn't be too bad. What do you think about adding a separate GH issue for allowing `@Size` on property parameters of type `String`?

Re: edge cases: I'm thinking of going with what's in #125, with the addition of an `@Also(...)` marker that says "Use these values for sure, then mix in other random values". I'm trying to carve out time to work through #125, but time is turning up scarce of late. [This branch](https://github.com/pholser/junit-quickcheck/tree/feature/125/modes) represents my work on it thus far. 

Re: `size` -- are you suggesting that there be a way to specify a lower bound (`min`) only, and if you do that, then let upper bound (`max`) effectively be `min + status.size()`? That sounds reasonable. Not sure how to do it in a way that doesn't disturb other clients of `@Size`. I'm open to suggestions.

**Comment by mspiegel** [comment]
Thanks for the feedback! I'm traveling and will have sporadic internet for the next week. I'll close this issue and open another one for String and Size. Should be easy to implement I can probably submit a PR. I have to think some more about the Collections size. I'm not sure what is the behavior that I want for my use case. And then to figure out how to generalize it to be useful for others.

With respect to @Also one related use case that will be helpful for me is to have a generator that only generates a finite number for prespecified values. Whatever is implemented for @Also will probably also work for this case.
