### ISSUE TITLE
Allow Encoded override of default StringGenerator in PropertiesGenerator

### ISSUE THREAD

**Issue by brentvukmer** [pholser/junit-quickcheck#152]
@pholser do you mind if I submit a PR for this?  Seems innocuous enough, and you've already done all the work of creating [the Encoded class](https://github.com/pholser/junit-quickcheck/blob/master/generators/src/main/java/com/pholser/junit/quickcheck/generator/java/lang/Encoded.java) :)

**Comment by pholser** [comment]
@brentvukmer Not at all -- eager to see what you come up with! Thanks!
