### ISSUE TITLE
`AssertionError` while shrinking

### ISSUE THREAD

**Issue by aelred** [pholser/junit-quickcheck#155]
In version 0.7, while executing a property test with the following signature:
```
public void testFoo(@Size(min=1000, max=5000) List<Foo> foos) throws Exception {
    ...
}
```

where `Foo` is a class with a generator `Foos` (which does not implement `doShrink`), I very infrequently get the following error:

```
java.lang.AssertionError: null
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$38(PropertyStatement.java:136)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        ...
```

It appears to be because there was an error while shrinking a parameter (probably a `NullPointerException`). This is likely an issue with my `Foos` generator, but the exception does not help me work out where the issue has occurred. It would be very helpful if the `AssertionError` included the original stack-trace to help with debugging issues with generators.

**Comment by pholser** [comment]
@aelred Thanks for your interest in junit-quickcheck! Would you mind to share your `Foos` generator, and a minimal definition of class `Foo`? It might help me replicate your issue.

**Comment by aelred** [comment]
Thanks @pholser, I love the library!

I attempted to reproduce the issue using random failures. I've found an example that will fail only occasionally in the way described above:

TestFoo.java
```
@RunWith(JUnitQuickcheck.class)
public class TestFoo {
    @Property
    public void testFoo(@Size(min=1000, max=5000) List<@From(Foos.class) Object> foo) {
        if (Math.random() > 0.99) {
            fail();
        }
    }
}
```

Foos.java
```
public class Foos extends Generator<Object> {
    public Foos() {
        super(Object.class);
    }

    @Override
    public Object generate(SourceOfRandomness random, GenerationStatus status) {
        if (random.nextFloat() > 0.99999) {
            throw new NullPointerException();
        }

        return new Object();
    }
}
```

I'll see if I can produce an example that fails more reliably.

**Comment by pholser** [comment]
@aelred I think I see the problem. When shrinking, we're doing this in `PropertyStatement.property()`:

                try {
                    shrink(params, args, seeds, shrinkControl, e);
                } catch (AssertionError ex) {
                    throw ex;
                } catch (Throwable ex) {
                    throw new AssertionError(**ex.getCause()**);
                }

That should almost certainly be `throw new AssertionError(ex)`.

Does that sound about right?

**Comment by pholser** [comment]
@aelred I'm dropping this change onto `master`. Will be in the next 0.8-alpha. Thanks for reporting this!

**Comment by pholser** [comment]
@aelred This is in 0.8 alpha 5.

Thanks for reporting!

**Comment by aelred** [comment]
Thanks, I'm glad I could help!
