### ISSUE TITLE
The readme should include some sample code

### ISSUE THREAD

**Issue by stephanenicolas** [pholser/junit-quickcheck#158]

**Comment by pholser** [comment]
@stephanenicolas I've added a very basic example to `README.md` on `master`. Will this suffice to resolve the issue? If not, what else would you like to see?

Thanks for your interest in junit-quickcheck!

**Comment by stephanenicolas** [comment]
@pholser Thx for doing so. I think it's still missing 3 sentences to explain QuickCheck philosophy. A link would not be enough, something really simple. 

/quote junit-quickcheck generates arbitrary data and tests your code against it. Explain whether or not data can be reproduced.. something like that. ;)

**Comment by pholser** [comment]
@stephanenicolas Understood. I think I underestimated how powerful the README can be as a first impression/quick start. I'll consider what to add. Thanks!

**Comment by pholser** [comment]
@stephanenicolas Sorry to get back to this so late. Have a look at #162, if you would? Hopefully this meets your desires?

Thanks again!
