### ISSUE TITLE
ValuesOf implementations introduce correlated behavior

### ISSUE THREAD

**Issue by fugu13** [pholser/junit-quickcheck#160]
I noticed when checking the source code that uses ValuesOf, while it makes sure all possible values are checked, it also introduces correlated behavior that can undesirably avoid areas of tests.

First, here's a stylized test for the behavior. This test will pass, despite the code failing if alpha and beta aren't both true or both false.

```java
import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.generator.ValuesOf;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

@RunWith(JUnitQuickcheck.class)
public class DoubleBooleanTest {
    @Property public void dependentTest(@ValuesOf boolean alpha, @ValuesOf boolean beta) {
        if((alpha && beta) || (!alpha && !beta)) {
            assertTrue(true);
        } else {
            assertTrue("Uh oh", false);
        }
    }
}
```

Remove the two ValuesOf annotations and it fails, as it should. While this example is stylized, the code I'm testing includes many boolean-flagged branches that overly correlated booleans could cause problems for. Similar issues exist for Enums.

I haven't traced all the implications, but I think a possible solution could be initializing each instance of a generator using ValuesOf with a randomized integer offset, then adding that offset in before taking the modulo. I'm not sure how to connect the randomized integer offset to the seed, though, which would be needed for reproducibility. Maybe initialize the integer in generate but only if not set yet?

**Comment by pholser** [comment]
@fugu13 A few things to note:

`@ValuesOf` made a lot more sense back when junit-quickcheck leveraged the `Theories` runner, whose default mode of execution was to run the property once for every element of the cross product of the sets of values generated for each theory parameter. So for a theory such as:

    enum Response { YES, NO, UNSURE }

    @Theory public void x(@ForAll int x, @ForAll boolean y, @ForAll Response r) {
        // ...
    }

the `Theories` runner would generate `Theory.sampleSize` values for each of the parameters, then execute `x` once for each combination. 100 * 100 * 100 = 1M executions. Ugh.

`@ValuesOf` came along and said that regardless of the sample size dictated on the `@Theory` marker, generate only the two values in `boolean`'s domain as values for `y`, and the three values in `Response`'s domain as values for `r`. 100 * 2 * 3 = 600 executions. Much better.

Sometime after 0.5, we abandoned the `Theories` runner and used our own `JUnitQuickcheck` runner, for better control of things like shrinking, error reporting, etc. This runner's mode is to generate `Property.trials` "tuples" of arguments, hence only `Property.trials` number of executions. In this context, `@ValuesOf` really doesn't make much sense. I consider it deprecated, but won't consider officially deprecating/targeting for removal until I get a handle on [adding exhaustive vs. sampling execution modes](https://github.com/pholser/junit-quickcheck/issues/125). When these modes are in play, probably you'll get the `@ValuesOf` behavior by default in "exhaustive" mode for `boolean` and `enum` parameters without having to annotated.

All this is to say, `@ValuesOf` probably isn't terribly useful at this point. I don't plan to address, and am hoping that exhaustive mode, along with the `@Only` and `@Also` parameter markers, get programmers most of what they'd need.

**Comment by fugu13** [comment]
Makes sense to me, and thanks for the background on the exhaustive execution mode work. I'll close this issue.
