### ISSUE TITLE
UUID generator

### ISSUE THREAD

**Issue by MichalKononenko** [pholser/junit-quickcheck#161]
A generator for random UUIDs seems like a good step forward. At the very least, the generator could wrap [UUID.randomUUID()](https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html).

I'm loving this library by the way! I can use this with Jackson to make as much random JSON as I will ever need!

**Comment by pholser** [comment]
@MichalKononenko Thanks for your interest in junit-quickcheck!

Would the machinery in class [RFC4122](https://github.com/pholser/junit-quickcheck/blob/master/generators/src/main/java/com/pholser/junit/quickcheck/generator/java/util/RFC4122.java) meet your needs?

**Comment by MichalKononenko** [comment]
Yep!
