### ISSUE TITLE
Support for showing what values were actually used?

### ISSUE THREAD

**Issue by ryanstull** [pholser/junit-quickcheck#171]
Hello, I'd like to say I very much like property based testing and I'm really glad to see you bringing it to Java!

Something I was trying to do was show which random values were actually used to test my properties.  Is there a setting for this?

**Comment by pholser** [comment]
@ryanstull Thanks for your interest! Currently there is no setting for accomplishing what you want. I wonder if logging these to a well-known SLF4J logger or some such would satisfy? Let me know.

There was a time where this is how we reported the seeds used -- maybe I can reinstate that plus the random values.

For complex values, will `toString()` be enough to report?

**Comment by ryanstull** [comment]
Yeah, if there was a mode where it could output the seed and toString of the random values to some log file, that'd be totally sufficient for my purposes! :)

**Comment by pholser** [comment]
@ryanstull Sorry it took so long to tackle this. Have a look on the above branch, if you would. I'm more than willing to fiddle with the format/content of the log messages. Thanks!

**Comment by pholser** [comment]
@ryanstull If no objections, I'll go ahead and merge the above PR. Let me know...thanks!

**Comment by ryanstull** [comment]
@pholser, Looks great!  Thanks a bunch
