### ISSUE TITLE
Only shrinking first of two parameters

### ISSUE THREAD

**Issue by csamak** [pholser/junit-quickcheck#175]
(Using version 0.7) I have a property with signature myProp(int, Point) where my Point generator is very similar to the one on the Shrinking documentation page.

When it fails, shrinks are only evaluated for the int. However, if I change the signature to myProp(Point, int), shrinks are only evaluated for the Point.

Is this a known issue? If not I can build a simple example that reproduces it.

**Comment by pholser** [comment]
@csamak I'm not aware of such an issue -- I'd appreciate a simple example for repro. Thanks!

**Comment by csamak** [comment]
Reproduced with LATEST:

```java
import com.pholser.junit.quickcheck.From;
import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.generator.GenerationStatus;
import com.pholser.junit.quickcheck.generator.Generator;
import com.pholser.junit.quickcheck.random.SourceOfRandomness;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;
import org.junit.runner.RunWith;

import java.util.Collections;
import java.util.List;

import static org.junit.Assert.fail;

@RunWith(JUnitQuickcheck.class)
public class Reproduce175 {
    public static class Other {}
    public static class OtherGenerator extends Generator<Other> {

        public OtherGenerator() {
            super(Other.class);
        }

        @Override
        public List<Other> doShrink(SourceOfRandomness random, Other larger) {
            System.out.println("tried to shrink!");
            return Collections.emptyList();
        }

        @Override
        public Other generate(SourceOfRandomness sourceOfRandomness, GenerationStatus generationStatus) {
            return new Other();
        }
    }

    @Property
    public void shrinksInt(int test, @From(OtherGenerator.class) Other other) {
        fail("Shrink me!");
    }

    @Property
    public void shrinksOther(@From(OtherGenerator.class) Other other, int test) {
        fail("Shrink me!");
    }
}
```

Only one `"tried to shrink!"` message is printed.

**Comment by pholser** [comment]
@csamak Thanks for this. I think I've got a handle on what was happening. Should have a PR available soon.

**Comment by pholser** [comment]
@csamak At your convenience, have a look at the PR above -- think this will help resolve your issue.

**Comment by pholser** [comment]
May take a while before I can get back to this -- other priorities bubbling up to the top. Will return to this when I can.

**Comment by pholser** [comment]
@csamak At your convenience, have a look at this latest PR. I've rethought the shrinking machinery a bit. It looks like this gives all parameters a chance to be shrunk.

**Comment by csamak** [comment]
Thanks for getting to this, I look forward to using it in the next release!

**Comment by pholser** [comment]
@csamak This should be in 0.8 beta 1.
