### ISSUE TITLE
Generating with the same seed doesn't always generate the same result

### ISSUE THREAD

**Issue by csamak** [pholser/junit-quickcheck#179]
Generating values with a predetermined seed doesn't always seem to work as expected.

With the same seed, different values are generated. To reproduce:

```java
import com.pholser.junit.quickcheck.From;
import com.pholser.junit.quickcheck.Property;
import com.pholser.junit.quickcheck.generator.GenerationStatus;
import com.pholser.junit.quickcheck.generator.Generator;
import com.pholser.junit.quickcheck.random.SourceOfRandomness;
import com.pholser.junit.quickcheck.runner.JUnitQuickcheck;
import org.junit.runner.RunWith;

import java.util.function.Function;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;

@RunWith(JUnitQuickcheck.class)
public class Reproduce {
    public static class Other {
        private final Number test;

        public Other(Number test) {
            this.test = test;
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof Other && test.equals(((Other) obj).test);
        }

        @Override
        public int hashCode() {
            return test.hashCode();
        }

        @Override
        public String toString() {
            return test.toString();
        }
    }

    public static class OtherGenerator extends Generator<Other> {

        public OtherGenerator() {
            super(Other.class);
        }

        @Override
        public Other generate(SourceOfRandomness random, GenerationStatus status) {
            return new Other(gen().type(Number.class).generate(random, status));
        }
    }

    @Property
    public void sameFuncTwice(
            Function<@From(OtherGenerator.class) Other, @From(OtherGenerator.class) Other> func,
            @From(OtherGenerator.class) Other test) {
        
        assertThat(func.apply(test), is(func.apply(test)));
    }
}
```

Stepping through the generator will reveal that random and status have the same seed for both calls when applying func. However, the number generate call doesn't return the same value.

Note: replacing Number.class with Integer.class makes it work properly.

**Comment by pholser** [comment]
Interesting. When many generators can satisfy a property parameter, unless otherwise directed one will be chosen at random with equal probability. But, perhaps, the seed of the randomness source for making those choices doesn't get transferred from the fixed seed chosen for the parameter.

Will investigate. Thanks!

**Comment by pholser** [comment]
May take a while before I can get back to this -- other priorities bubbling up to the top. Will return to this when I can.

**Comment by pholser** [comment]
@csamak Sorry for taking so long to get to this.

junit-quickcheck creates sources of randomness in a few places:
* One for each property parameter
* One for the generator repository to use, in situations where it must choose from a set of candidate generators
* One for each on-the-fly lambda generator (so it can respond the same way to lambda invocations with the same args)

Here, it appears that `gen().type(Number.class)` is making a choice among several conformant generators, but the source of randomness is hidden from the generator writer, so we don't get to control it.

Perhaps adding `gen(random)` would help. PR forthcoming.

**Comment by pholser** [comment]
@csamak At your convenience, have a look at the above PR. Looks like this may have solved your issue.

Here's your generator using the additional `gen()` signature:

```java
    public static class OtherGenerator extends Generator<Other> {
        public OtherGenerator() {
            super(Other.class);
        }

        @Override public Other generate(SourceOfRandomness r, GenerationStatus s) {
            return new Other(gen(r).type(Number.class).generate(r, s));
        }
    }
```

**Comment by csamak** [comment]
Looks good to me, thanks!

**Comment by pholser** [comment]
Excellent. Will merge shortly. Should be in next 0.8 alpha. At some point soon, I'll settle on a feature set for 0.8 -- I want to for sure roll in resolutions for your shrinking issues.

Who knows, 0.8 may just leap to 1.0. 8^)
