### ISSUE TITLE
Add a gen().type() overload that supports componentTypes

### ISSUE THREAD

**Issue by csamak** [pholser/junit-quickcheck#181]
[This comment](https://github.com/pholser/junit-quickcheck/issues/167#issuecomment-310171493) on a previous issue suggests adding a gen().type() overload that supports componentTypes.

I think that would be a big improvement over working with generator classes directly - this is just a new issue to track that.

In general the model for generating types that are composed of other types (without match the component generator model) seems like it could be improved, but I don't have many concrete ideas yet - will add issues as they come.

**Comment by pholser** [comment]
@csamak There is `gen().make(Class<?>, component types)` -- would that suit your needs?

**Comment by csamak** [comment]
Yes, it works. However I'd like to avoid thinking about specific generators and would rather think about types (I have multiple generators for the same types - if I use `make()` some part of my code must be aware of the list of generators).

This is low priority for me though, since I'm using `.field(getClass().getDeclaredField(...))` as a workaround.

**Comment by pholser** [comment]
@csamak OK, thanks for the feedback. I totally understand the desire to focus on the types and not specific generators -- will see how easy retrofitting `gen().type()` would be.

**Comment by pholser** [comment]
@csamak At your convenience, have a look at the PR above and let me know whether this will do the trick for you. If it does, I'll merge it and add some additional documentation. Thanks!

**Comment by csamak** [comment]
I think that does it - thanks!

**Comment by pholser** [comment]
Great! Thanks for the suggestion. It turned out easier than I thought.
