### ISSUE TITLE
Generate Entity with Hashmaps with min size=1

### ISSUE THREAD

**Issue by Baasie** [pholser/junit-quickcheck#186]
Hi,

I was wondering how I can generate a HashMap<LocalDate, Pojo> in another generator with size =1.
The LocalDate and Pojo generators are both available.

I did succeed in creating an Entity generator with a HashMap with gen().type(HashMap.class).generate(...

But this way we got a lot of empty hashmap and sometimes they are filled. So i want to pass in the annotation Size with gen().make().configure() but then we get an error that the components are not filled correct.

Can you show me an example on how to do this correctly?!

many thanx !

**Comment by pholser** [comment]
@Baasie Do you have a minimal example you can show me? I might be able to correct it...

**Comment by pholser** [comment]
One possibility: `gen().type(HashMap.class).filter(m -> !m.isEmpty()).generate(...)`

**Comment by Baasie** [comment]
`public class PerformanceHistoryGenerator extends Generator<PerformanceHistory> {


    public PerformanceHistoryGenerator() {
        super(PerformanceHistory.class);
    }

    @Override
    public PerformanceHistory generate(SourceOfRandomness sourceOfRandomness, GenerationStatus generationStatus) {
        return new PerformanceHistory(
            gen().type(HashMap.class).generate(sourceOfRandomness, generationStatus),
            gen().type(HashMap.class).generate(sourceOfRandomness, generationStatus)
        );
    }
}`

The filter did not work (at least it generated for 15s then we cancelled it)

If we do:
`            gen().make(HashMapGenerator.class).generate(sourceOfRandomness, generationStatus),
`

Then we get the following:
java.lang.IllegalArgumentException: Needed 2 components for class com.pholser.junit.quickcheck.generator.java.util.HashMapGenerator, but got 0


Both HashMap has 2 components, LocalDate and CustomPojo. Both made available with a generator.

Thanx!

**Comment by pholser** [comment]
@Baasie Latest snapshot modified `gen().type()` so that you can say:

    `gen().type(HashMap.class, LocalDate.class, Pojo.class)`

to provide component generators. I'll publish this as a fresh 0.8 alpha. After a satisfactory resolution to #175, I'll declare a 0.8 RC.

**Comment by pholser** [comment]
You may also be able to say:

    `gen().make(HashMapGenerator.class, LocalDateGenerator.class, PojoGenerator.class)....`

**Comment by Baasie** [comment]
Cool gonna wait for that, thanx!

**Comment by pholser** [comment]
@Baasie 0.8 alpha 8 should be available -- give it a try!

**Comment by pholser** [comment]
@Baasie Let me know whether 0.8 alpha 8 satisfies this need for you -- thanks!

**Comment by Baasie** [comment]
Hi @pholser just got back from my holiday, will check next week for you when I am back on that project.

I'll keep you posted!

**Comment by pholser** [comment]
@Baasie Hi, any news on whether latest releases satisfy this need? Thanks for any update you can provide.

**Comment by Baasie** [comment]
Hi @pholser my apologies. Did not have enough time to check, hopefully will get some time this week!

**Comment by pholser** [comment]
@Baasie No worries -- it turns out what I was suggesting didn't do the trick, because it doesn't ever get a chance to generate a non-empty map.

How about this instead, to guarantee that the `HashMap`s given to a generated `PerformanceHistory` have at least one key-value pair?

```java
public class PerformanceHistory {
    private final HashMap<LocalDate, Integer> h1;
    private final HashMap<LocalDate, Integer> h2;

    public PerformanceHistory(
        HashMap<LocalDate, Integer> h1,
        HashMap<LocalDate, Integer> h2) {

        this.h1 = h1;
        this.h2 = h2;
    }

    public boolean empty() {
        return h1.isEmpty() && h2.isEmpty();
    }
}

public class PerformanceHistoryGenerator extends Generator<PerformanceHistory> {
    public PerformanceHistoryGenerator() {
        super(PerformanceHistory.class);
    }

    @SuppressWarnings("unchecked")
    @Override
    public PerformanceHistory generate(
        SourceOfRandomness random,
        GenerationStatus status) {

        Generator<HashMap> maps =
            gen().type(HashMap.class, LocalDate.class, Integer.class);
        HashMap<LocalDate, Integer> map1 = maps.generate(random, status);
        HashMap<LocalDate, Integer> map2 = maps.generate(random, status);

        map1.put(
            gen().type(LocalDate.class).generate(random, status),
            gen().type(Integer.class).generate(random, status));
        map2.put(
            gen().type(LocalDate.class).generate(random, status),
            gen().type(Integer.class).generate(random, status));

        return new PerformanceHistory(map1, map2);
    }
}
```

**Comment by pholser** [comment]
@Baasie Another option, if you're willing to mark your domain class with a junit-quickcheck annotation:

```java
public class PerformanceHistory {
    private final HashMap<LocalDate, Integer> h1;
    private final HashMap<LocalDate, Integer> h2;

    public PerformanceHistory(
        @Size(min = 1, max = 5) HashMap<LocalDate, Integer> h1,
        @Size(min = 1, max = 5) HashMap<LocalDate, Integer> h2) {

        this.h1 = h1;
        this.h2 = h2;
    }

    public boolean empty() {
        return h1.isEmpty() && h2.isEmpty();
    }
}

@RunWith(JUnitQuickcheck.class)
public class PerformanceHistoryProperties {
    @Property(trials = 10) public void alsoNotEmpty(
        @From(Ctor.class) PerformanceHistory h) {

        assertFalse(h.empty());
    }
}
```

This way, you don't write a `PerformanceHistoryGenerator`.

**Comment by pholser** [comment]
@Baasie I also figured out why tacking on the `filter` to the `HashMap` generator like so:

```java
    gen().type(HashMap.class, LocalDate.class, Integer.class)
        .filter(m -> !m.isEmpty())
```

doesn't get the result we were hoping for. I'll see if I can come up with a resolution for this issue.

**Comment by Baasie** [comment]
Cool! I did not have a lot of time on my hands lately sorry. Been switching assignments just now. I will see if I can do some more in the upcoming weeks. 

We got it to work in the same way as your first example. But I feel like it could be easier with at least that filtering or something.

Thanx for the hard work!

**Comment by pholser** [comment]
@Baasie 0.8 beta 2 should allow the `filter()`ing solution to advance and actually start to produce non-empty values. If that works for you, I think we can consider this issue resolved.

**Comment by pholser** [comment]
I'm considering this resolved. Let me know if for some reason this solution isn't satisfactory.
