### ISSUE TITLE
assumption compatibility with http://google.github.io/truth and junit 4.12

### ISSUE THREAD

**Issue by matonthecat** [pholser/junit-quickcheck#190]
Hi,

Using google truth assumptions like this one 

`assume().that(lookup).isIn(items);`

in a quickcheck property check, I get the behavior that instead of issuing an assumption violation, the PropertyVerifier wraps the AssumptionViolatedException into an AssertionError. Digging deeper, I found that PropertyVerifier handles org.junit.AssumptionViolatedException correctly, but not org.junit.internal.AssumptionViolatedException. 

https://github.com/pholser/junit-quickcheck/blob/6f74a5e27f6cfddc9240dd1cbaed9b8774cc8ccb/core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyVerifier.java#L79

org.junit.AssumptionViolatedException is deprecated, and inherits from org.junit.internal.AssumptionViolatedException.

Truth guys inherit from org.junit.internal.AssumptionViolatedException, however. And though they promised to change this but probably changed their plans.

https://github.com/google/truth/blob/1fc8c22ab3e36c5a1565070b21c5428abe95b295/core/src/main/java/com/google/common/truth/TruthJUnit.java#L72

It's a minor issue, I can live without the google/truth assumption feature. Just wanted to make you aware.
best
Matthias

**Comment by pholser** [comment]
@matonthecat Thanks for the note! This should be a straighforward change -- I'll get it in soon.

**Comment by pholser** [comment]
@matonthecat Have a look at the above PR, if you would -- if you're satisfied, I'll merge. Cheers!

**Comment by matonthecat** [comment]
Looks good. Thanks for the change! Didn't expect you'd pick this up so close to Christmas.

**Comment by pholser** [comment]
@matonthecat Great, thanks! This is merged, will be released in either 0.8 final or a preceding 0.8 beta.
