### ISSUE TITLE
Generating multiple POJOs that share data

### ISSUE THREAD

**Issue by menzenski** [pholser/junit-quickcheck#192]
Hi, @pholser first of all thanks for all the work you've put into junit-quickcheck!

I often want to test behavior around pairs of objects that share data, e.g.,

```java
class Customer {
    String id;
}

class Order {
    String customerId;
}
```

When testing a customer-order pair, I frequently need to adjust the generated objects at the beginning of each test method to set a field on one object to match a field on the other member of the pair:

```java
@Property
public void customerOrderProperty(Customer customer, Order order) {
    order.setCustomerId(customer.getId); // would like to avoid having to do this
    /* do testing */
}
```
or alternatively, define a "pair" class which contains one member of each type and add a generator for that pair class, which can set them appropriately:

```java
@Property
public void customerOrderProperty(CustomerOrderPair pair) {
    Customer customer = pair.getCustomer();
    Order order = pair.getOrder();
    /* do testing */
}
```

Is there a way to do this in a way that doesn't require adjusting property parameters in each test method?

It _feels_ like maybe there's a way to do this with [`GenerationStatus.Key#setValue`](https://github.com/pholser/junit-quickcheck/blob/ad2e9f9e1eb9461f1804cf01891149df87b770f5/core/src/main/java/com/pholser/junit/quickcheck/generator/GenerationStatus.java#L58), but I haven't yet found out how.

**Comment by pholser** [comment]
@menzenski Thanks for your interest! I'll think about this for a bit and get back to you soon.

**Comment by pholser** [comment]
@menzenski I think your best bet is something along the lines of your `CustomerOrderPair` -- something that can be generated such that the constraint of both customer and order sharing the key bit of info is enforced.

```java
class CustomerOrderContext {
    Customer c;
    Order o;
}

class CustomerOrderContexts extends Generator<CustomerOrderContext> {
    generate(r, s) {
        Customer c = new Customer("123");
        Order o = new Order("456");
        o.setCustomerId(c.id());
        return new CustomerOrderContext(c, o);
    }
}

// or maybe...
class CustomerOrderContextsByFields extends Generator<CustomerOrderContext> {
    generate(r, s) {
        CustomerOrderContext context = gen().fieldsOf(CustomerOrderContext.class)
            .generate(r, s);
        context.o.setCustomerId(c.id());
        return context;
    }
}
```

**Comment by menzenski** [comment]
@pholser thanks, that's about what I've been doing. I'm marking this issue as closed.

If I come up with a less verbose method of achieving the same behavior, I'll try to get a PR together.
