### ISSUE TITLE
Messages aren't easy to understand

### ISSUE THREAD

**Issue by Jiehong** [pholser/junit-quickcheck#193]
Hello,

I think messages returned for failed cases aren't very easy.

Here is an example:

```java
  @Property
  public void firstTest(final List<Integer>values) {
    final ExerciseOne instance = new ExerciseOne();
    Assert.assertTrue(instance.absoluteAverage(values) >= 0);
  }
```

Here is the message I get:

```java
java.lang.AssertionError: Property firstTest falsified via shrinking: null
Shrunken args: [[-1209279219, 938232675]]
Original failure message: [null]
Original args: [[-1209279219, -1986811869]]
Seeds: [7190051195178127153]
```

Here, I thought that the failing case is the input `null`, but it's not the case, as this check is manually checked in another case.

Instead, I feel like it's "[-1209279219, 938232675]", even though I thought the lib tried to provide a list of list of integers at first (it's an overflow issue here).

Could the failing case be clearer from the log messages?

For example, what about:

``` java
java.lang.AssertionError: Property named 'firstTest' failed with the following shrunk arguments: [-1209279219, 938232675]
First value found to also provoke a failure: [-1209279219, -1986811869]
Seeds: [7190051195178127153]
```

Version tested: 0.7 & 0.8-beta-2.

**Comment by Jiehong** [comment]
I had quick check at the code, and it seems it's done there: https://github.com/pholser/junit-quickcheck/blob/ad2e9f9e1eb9461f1804cf01891149df87b770f5/core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyFalsified.java

If you're opened to PRs, perhaps I can have a look and change it to something better we agree upon?

**Comment by pholser** [comment]
@Jiehong Absolutely open to rephrasing failed assertions, and PRs. Thanks!

The `null` is the message associated with the failed assertion. In the case of `assertTrue(instance.absoluteAverage(values) >= 0)`, that message is `null`. Something like `assertTrue("Need a non-negative value", instance.absoluteAverage(values) >= 0)` would yield the message `Need a non-negative value` if it were to fail.

**Comment by Jiehong** [comment]
Right, so perhaps this message presence should be checked for non-nullity I guess.

I'll have a look, and offer a PR then :)
