### ISSUE TITLE
Compile error in sample code

### ISSUE THREAD

**Issue by taka2** [pholser/junit-quickcheck#194]
Hi, 

I read the v0.7 document and I found the compile error in sample code.
http://pholser.github.io/junit-quickcheck/site/0.7/usage/complex-types.html

class PolygonGenerator
`int xs = new int[numberOfPoints];`
-> int[] xs = ...

`int ys = new int[numberOfPoints];`
-> int[] ys = ...

class TrafficTrackers
`@Override public Counter generate(`
-> @Override public TrafficTracker generate(

Is that right?

**Comment by pholser** [comment]
@taka2 Thanks for reporting this! The declarations of `xs` and `ys` are clearly errors. The `@Override` with a capital `O` is correct. I will correct the errors on master.

**Comment by taka2** [comment]
@pholser Thank you for your reply!
In class TrafficTrackers, I misspelled.
@Override is correct.
I think Return Type of generate method is not Counter but TrafficTracker.

**Comment by taka2** [comment]
sorry, capital O is correct.

**Comment by pholser** [comment]
Right you are. Correcting return type in follow-on PR.

**Comment by taka2** [comment]
Thank you.

**Comment by pholser** [comment]
No worries, thanks for your interest!
