### ISSUE TITLE
Mapped Generation does not seem to do what I think it should do

### ISSUE THREAD

**Issue by jlink** [pholser/junit-quickcheck#199]
Here's my property:

```
	@Property()
	public void shouldShrinkTo105(
			@From(DivisibleBy5.class) //
			@When(seed = -4386629332000517955L) //
					int i //
	) {
		System.out.println(i);
	}

	public static class DivisibleBy5 extends Generator<Integer> {

		public DivisibleBy5() {
			super(Integer.class);
		}

		@Override
		public Integer generate(SourceOfRandomness random, GenerationStatus status) {
			return gen().type(int.class) //
					.map(i -> Math.abs(i * 5)) //
					.filter(i -> i > 100) //
					.filter(i -> i < 1000) //
					.generate(random, status);
		}
	}
```
What I think it should produce is multiples of 5 between 100 and 1000.
However the output looks like the map function is not being used:

```
447
882
250
842
826
920
357
861
117
135
958
867
638
252
143
...
```

I'm not sure I'm understanding the purpose of map correctly.

**Comment by pholser** [comment]
@jlink Thanks for this -- will investigate.

**Comment by pholser** [comment]
@jlink I think the integer multiplication is overflowing in some cases.

For example, using the seed you provided, the first integer to be handed to the `map()` function is `-1233545336`. That multiplied by `5` ordinarily would be `-6167726680`, but that has magnitude too great for a 32-bit `int`. Instead, you get `-1872759384`.

**Comment by jlink** [comment]
Many thanks. Should have been obvious - but wasn't!

**Comment by pholser** [comment]
@jlink Side note: TIL you can use (JDK >= 8) [methods on java.lang.Math](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#multiplyExact-int-int-) to perform the usual arithmetic operations on `int` and `long` that raise exceptions on overflow.
