### ISSUE TITLE
Lack of good example suite?

### ISSUE THREAD

**Issue by fulara** [pholser/junit-quickcheck#200]
Please add some extensive example suite, 
Right now I am googling around for quickcheck for java and top 2 results are yours and `https://github.com/ncredinburgh/QuickTheories` QuickTheorises has nice welcome page where it explain most basic concepts, its not ideal but its definitely better than shown here.

**Comment by asarkar** [comment]
+1. Where many excellent open source libraries fall short is that their docs are a big "read the code or go f yourself".

**Comment by pholser** [comment]
@fulara @asarkar Thanks for your interest!

By "example suite", do you mean documentation, or a separate set of code included with the project?

Are you looking for more content in the README?

There is a site: http://pholser.github.io/junit-quickcheck/site/0.8/ -- should I be calling more attention to it from the README?

**Comment by pholser** [comment]
@fulara @asarkar At your convenience, have a look at the above PR and let me know what you think.

Not sure whether this qualifies as a "good" example suite -- I pulled most of this from the `junit-quickcheck-scratchpad` project. It will be built and published with every release of junit-quickcheck.

Any and all feedback would be much appreciated. Thanks!

**Comment by fulara** [comment]
Honestly, the update of readme.md would probably did it for me :) Last time i simply did not find the link and I searched the code for some samples but couldnt find any. Its definitly better now!

**Comment by pholser** [comment]
Right on. Thanks for getting back so quickly! I'll merge this, and cut a 0.8.1 soon.
