### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by kshirsagarps** [pholser/junit-quickcheck#204]
Please add licensing information for this library.

**Comment by pholser** [comment]
Thanks for your interest!

Would these references suffice?

https://github.com/pholser/junit-quickcheck/blob/master/conf/MIT-LICENSE.txt
http://pholser.github.io/junit-quickcheck/site/0.8.1/license.html

**Comment by pholser** [comment]
@kshirsagarps Checking in on this issue -- do the above references satisfy this request?

**Comment by pholser** [comment]
I am considering this issue resolved, not having heard back from the originator and having shown the licensing info.
