### ISSUE TITLE
`gen().type(List.class, String.class).generate(r,s)` generates a List<Zilch>

### ISSUE THREAD

**Issue by Allsimon** [pholser/junit-quickcheck#225]
See #226 for a reproduction case

**Comment by pholser** [comment]
@Allsimon I think I've got this fixed. At your convenience, have a look at the above PR and see how it works for you. Sorry for the trouble, but thanks for pointing out the problem.

**Comment by Allsimon** [comment]
@pholser thank you for fixing this so quickly.
It works fine now :)

**Comment by pholser** [comment]
No worries! This is merged into 0.8-branch and master.

**Comment by Sir4ur0n** [comment]
Any idea when you will publish a new release including this change and the shrinker change?

**Comment by pholser** [comment]
@Sir4ur0n Probably within the next couple of weeks.

**Comment by Sir4ur0n** [comment]
Hey @pholser, sorry to ping every time, but do you think you could release soon? I actually need this fix (and the new shrinker) for downstream libraries and projects. Thank you!

**Comment by pholser** [comment]
@Sir4ur0n Hi Julien, sorry for the delay -- undergoing a job change, and am finding little time to revisit j-q. How about this: I will commit to cutting a 0.9 release this weekend (18-19 May). Sound good?

**Comment by Sir4ur0n** [comment]
That would be awesome, thank you! No worries, everybody had personal
matters ;)

Le lun. 13 mai 2019 à 22:22, Paul Holser <notifications@github.com> a
écrit :

**Comment by Sir4ur0n** [comment]
Hi again, I see you have prepared the release [here](https://github.com/pholser/junit-quickcheck/releases) but I couldn't find the JAR neither in Maven Central nor in JCenter. Would you mind publishing it? ^^'

**Comment by pholser** [comment]
@Sir4ur0n Hi Julien -- I use the Maven release plugin to do lots of release-related stuff, and it's currently failing when trying to sign artifacts. I recently uploaded a new key to MIT's GPG key server, and I'm wondering whether there's an issue there. As soon as I've got that ironed out and the artifacts at Maven Central, I'll let you know here and the Google group there.

**Comment by pholser** [comment]
0.9 appears to have hit Maven central.

**Comment by Sir4ur0n** [comment]
I just realized I never replied here: thank you, I updated my library to use 0.9 ;)

Cheers!

**Comment by pholser** [comment]
@Sir4ur0n No worries -- happy to help!
