### ISSUE TITLE
Please refrain from using Math.abs(int) when "non-negative integer" is required

### ISSUE THREAD

**Issue by vlsi** [pholser/junit-quickcheck#233]
`Math.abs(Integer.MIN_VALUE)` produces `Integer.MIN_VALUE`, so `Math.abs` does not produce "non-negative integers".

Sample pages with issues:
https://pholser.github.io/junit-quickcheck/site/0.9/usage/configuring.html
https://pholser.github.io/junit-quickcheck/site/0.9/usage/complex-types.html
https://github.com/pholser/junit-quickcheck/blob/61e751ceb55cb767d7ef150959df0244543fcd64/examples/src/test/java/com/pholser/junit/quickcheck/examples/number/IntegralGenerator.java#L47

**Comment by pholser** [comment]
@vlsi Thanks for this. Will adjust.

**Comment by pholser** [comment]
@vlsi Check out the PR above -- let me know whether or not this will suffice. Thanks!

**Comment by vlsi** [comment]
It looks ok, so people might even learn that the should not try `Math.abs(MIN_VALUE)` at home :)
