### ISSUE TITLE
Optimize GeneratorRepository#composeWeighted and #oneOf when only one generator matches

### ISSUE THREAD

**Issue by vlsi** [pholser/junit-quickcheck#242]
Currently `junitquickcheck` produces `CompositeGenerator` all over the place even for cases when single generator is used (e.g. single `@From`).

That impacts performance, and it complicates analysis/debugging (extra `CompositeGenerator` wrapper object is present in debugger, yet it does not really matter)

**Comment by pholser** [comment]
@visi Understood. If I'm understanding correctly, the proposed change would be that if a generator search results in a single generator, junit-quickcheck should not wrap it in a composite?

**Comment by vlsi** [comment]
Yes. The proposed change is basically a single line change

**Comment by pholser** [comment]
@visi This should now be on both `0.9-branch` and `master`.
