### ISSUE TITLE
Support Iterator-like style for shrink implementation

### ISSUE THREAD

**Issue by vlsi** [pholser/junit-quickcheck#243]
Currently shrink causes lots of objects to be created because `doShrink` should return `List`.

It guess it would be better if shrinks could be added iteratively, so the verifier could pick objects and verify them. If property still fails, it could try shrinking the object that fails.

I guess it would produce more targeted results while current API does not make it clear how many shrink results should be produced.

**Comment by pholser** [comment]
@visi Sounds reasonable -- I'll investigate.

**Comment by vlsi** [comment]
I just realized it seems to duplicate
https://github.com/pholser/junit-quickcheck/issues/220

**Comment by vlsi** [comment]
This duplicates https://github.com/pholser/junit-quickcheck/issues/220
