### ISSUE TITLE
License Text is Not Included in Source

### ISSUE THREAD

**Issue by jsuskalo** [pholser/junit-quickcheck#251]
While the .pom file *does* specify that this project uses the MIT license, the full text of the MIT license does not appear to be included anywhere within the project, and as a result, if I understand correctly, all copyright for the entire project is still held by the original authors, which means that anyone who may want to use it in production, for example, will feel that this would be a significant risk and not use it as a result.

The fix should be fairly easy, just add a LICENSE.txt file in the root of the project with the full text of the MIT license.

**Comment by pholser** [comment]
@jsuskalo Thanks for this. Would you be willing to submit a pull request for this change?

**Comment by jsuskalo** [comment]
Pull request #252 has been made to resolve this issue.

**Comment by pholser** [comment]
Merged. Thanks!
