### ISSUE TITLE
API Request: Make SourceOfRandomness's delegate accessible

### ISSUE THREAD

**Issue by rohanpadhye** [pholser/junit-quickcheck#269]
Is it possible to make [`SourceOfRandomness#delegate`](https://github.com/pholser/junit-quickcheck/blob/99c0f9b71c7ef2a50a7842f8d7971cf0c005930f/core/src/main/java/com/pholser/junit/quickcheck/random/SourceOfRandomness.java#L55) accessible to sub-classes? Either by making the field `protected` or by adding a public `getDelegate()` method to the class. Right now, extending `SourceOfRandomness` is annoying because sub-classes need to carry around their own copy of a delegate (e.g. see JQF's [`FastSourceOfRandomness`](https://github.com/rohanpadhye/JQF/blob/5e808304b5c6f72778c17f22ca9426ed43a1b4f6/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/junit/quickcheck/FastSourceOfRandomness.java#L55-L60)).

**Comment by pholser** [comment]
@rohanpadhye Thanks for this. Sounds like a reasonable idea -- will investigate.

**Comment by pholser** [comment]
@rohanpadhye Would a `protected` method `delegate()` on `SourceOfRandomness` suffice? I'm a bit reluctant to make it `public` -- if a non-subclass client wants a `j.u.Random`, there is already `toJDKRandom()`.

**Comment by rohanpadhye** [comment]
Yup, a `protected` accessor works. It is only useful as an extension mechanism, and does not have to be exposed to the outside world.

**Comment by pholser** [comment]
@rohanpadhye This should be available now on 0.9-branch.

I'll probably cut a 0.9.4 release soon.

**Comment by rohanpadhye** [comment]
Awesome, thanks @pholser!
