### ISSUE TITLE
Shrinking on failures

### ISSUE THREAD

**Issue by pholser** [pholser/junit-quickcheck#32]
May require fiddling with the Theories runner?

**Comment by jesseshieh** [comment]
@pholser, thanks for this great library! For me, shrinking on failures is the top reason I don't use junit-quickcheck more often. Maybe it would be helpful to port over functionaljava's Shrink object? 
https://github.com/functionaljava/functionaljava/blob/master/core/src/main/java/fj/test/Shrink.java

**Comment by pholser** [comment]
@jesseshieh Thanks!

I was considering trying to crack open the Theories runner to try to get it to inject new (shrunken) tests into the suite when a failure is detected. I wonder if a JUnit Rule would be more appropriate and less work. Will check it out -- thanks for reminding me!

**Comment by pholser** [comment]
I'm going to tackle this. It will probably mean a break from the Theories machinery, and writing junit-quickcheck's own runner. Will have to decide whether to support both the Theories-based stuff and the new-runner-based stuff at some point. I am hopeful that we can abandon the Theories stuff at some point.

**Comment by pholser** [comment]
@jesseshieh I have pushed a working branch called `shrink` that has the beginnings of a `JUnitQuickcheck` test runner. My intent is that if it detects a failure in a `@Property` (replacement for `@Theory) method, to attempt to shrink the values that caused the failure, re-running the property with shrunken values until they can't be shrunk anymore or until the property passes; at which point we report a failure with the smallest values that caused the failure.

My initial thought is to have `Generators` support a `shrink(T)` method, the default impl of which gives an empty set of shrunken values. For this to work, on an execution of the property method, we'd need to hang onto the generators used, to ensure they can shrink the values on a property failure.

Would you be willing to help implement this, or offer suggestions?

**Comment by PascalSchumacher** [comment]
Thanks for implementing this. :+1: 

Now I'll just have to wait till I can use java 8 at work :/.

**Comment by pholser** [comment]
@PascalSchumacher No worries Pascal, thanks for your interest!

I am anticipating that the shrinking strategies here will need some more love, but at least there will be something for people to try, and hopefully suggest improvements.
