### ISSUE TITLE
Problem with Enums

### ISSUE THREAD

**Issue by vitekkor** [pholser/junit-quickcheck#331]
I have an enum class and I want to generate it from [EnumGenerator](https://github.com/pholser/junit-quickcheck/blob/1ba34f260e39e6937e23434509a772d3eb9dabe4/core/src/main/java/com/pholser/junit/quickcheck/internal/generator/EnumGenerator.java)
```kotlin
enum class Direction {
        RIGHT,   
        UP_RIGHT, 
        UP_LEFT, 
        LEFT,  
        DOWN_LEFT,  
        DOWN_RIGHT, 
        INCORRECT; 

        fun opposite(): Direction = when (this) {
            RIGHT -> LEFT
            UP_RIGHT -> DOWN_LEFT
            UP_LEFT -> DOWN_RIGHT
            LEFT -> RIGHT
            DOWN_LEFT -> UP_RIGHT
            DOWN_RIGHT -> UP_LEFT
            INCORRECT -> INCORRECT
        }

        fun next(): Direction {
            return when (this) {
                DOWN_RIGHT -> RIGHT
                INCORRECT -> throw IllegalArgumentException()
                else -> values()[ordinal + 1]
            }
        }

        fun isParallel(other: Direction) =
            this != INCORRECT && other != INCORRECT &&
                    (this == other || opposite() == other)
    }
```
but a "com.pholser.junit.quickcheck.internal.ReflectionException: java.lang.InstantiationException: com.pholser.junit.quickcheck.internal.generator.EnumGenerator" is thrown. It is thrown by this method ([Reflection](https://github.com/pholser/junit-quickcheck/blob/1ba34f260e39e6937e23434509a772d3eb9dabe4/core/src/main/java/com/pholser/junit/quickcheck/internal/Reflection.java))
```java
public static <T> T instantiate(Class<T> clazz) {
        try {
            return clazz.newInstance();
        } catch (Exception ex) {
            throw reflectionException(ex);
        }
    }
```
It is called from here `return instantiate(generatorType);` ([ParameterTypeContext](https://github.com/pholser/junit-quickcheck/blob/1ba34f260e39e6937e23434509a772d3eb9dabe4/core/src/main/java/com/pholser/junit/quickcheck/internal/ParameterTypeContext.java#L295))
```java
private Generator<?> makeGenerator(
        Class<? extends Generator> generatorType) {

        Constructor<? extends Generator> ctor;

        try {
            // for Ctor/Fields
            ctor = findConstructor(generatorType, Class.class);
        } catch (ReflectionException ex) {
            return instantiate(generatorType);
        }

        return instantiate(ctor, rawParameterType());
    }
```
Okey. I solved this by writing my own generator similar to yours
```kotlin
class EnumGenerator(private val enumType: Class<*>) : Generator<Enum<*>>(Enum::class.java) {
    override fun generate(random: SourceOfRandomness, status: GenerationStatus): Enum<*> {
        val values: Array<out Any> = enumType.enumConstants
        val index = random.nextInt(0, values.size - 1)
        return values[index] as Enum<*>
    }

    override fun canShrink(larger: Any): Boolean {
        return enumType.isInstance(larger)
    }
}
```
But when i try to generate with it i get exception: "java.lang.IllegalArgumentException: The generator class java.lang.Enum named in @com.pholser.junit.quickcheck.From on parameter arg0 does not produce a type-compatible object". 
It have been thrown by this method in [ParameterTypeContext](https://github.com/pholser/junit-quickcheck/blob/1ba34f260e39e6937e23434509a772d3eb9dabe4/core/src/main/java/com/pholser/junit/quickcheck/internal/ParameterTypeContext.java#L295)
```java
private void ensureCorrectType(Generator<?> generator) {
        for (Class<?> each : generator.types()) {
            if (!maybeWrap(resolved.getRawClass())
                .isAssignableFrom(maybeWrap(each))) {

                throw new IllegalArgumentException(
                    format(
                        EXPLICIT_GENERATOR_TYPE_MISMATCH_MESSAGE,
                        each,
                        From.class.getName(),
                        parameterName));
            }
        }
    }
```
it turns out that `maybeWrap(resolved.getRawClass()).isAssignableFrom(maybeWrap(each))` is equal to false.

I debugged it and when I tried this code it returned true.
```java
maybeWrap(each).isAssignableFrom(maybeWrap(resolved.getRawClass())) 
```
I'm not sure if just changing your condition to mine will solve the problem, as there may be problems with other generators. But I'm just trying to describe my research to you in as much detail as possible.

**Comment by pholser** [comment]
@vitekkor -- could you post your test class? It might help me figure out what's going on.

AFAIK, you should be able to write properties with parameters of enum types without having to name `@From(EnumGenerator.class)`.

**Comment by vitekkor** [comment]
I'm so sorry. Everything worked, as I removed the @From annotation.
If you still want to take a look at my test class, this is it.
```kotlin
@RunWith(JUnitQuickcheck::class)
class Tests {
    @Property
    @Tag("2")
    //FIXME
    fun oppositeDirectionTest(@From(EnumGenerator::class) this_: Direction) {
        //some actions
    }
}
```
But the issue can be closed. Thanks! Sorry one more time
