### ISSUE TITLE
Very slow test performance for theories with three or more arguments

### ISSUE THREAD

**Issue by sacundim** [pholser/junit-quickcheck#39]
I've just gotten started using the library, and one nasty problem I've noticed is that when I write a theory with three arguments, execution slows down to a crawl.

I've run the VisualVM sampler against the offending tests, and I see the following:

1. In the Call Tree (top-down) view, the bulk of the total wall-clock and CPU time (c. 99.8% in my scenario) is spent in `org.junit.contrib.theories.Theories$TheoryAncho.runWithAssignment()`.
2. In the Hot Spots view (bottom-up, self time), the dominating methods are `java.util.Random.nextDouble()` and `java.lang.reflect.AccessibleObject.getAnnotations()`.  The self time of these two methods adds up to nearly all of the runtime of the unit tests.

I can share the VisualVM snapshot if that helps.  I can't share the code that's giving me the issue right now, but I can try writing an isolated test case if that helps.

**Comment by pholser** [comment]
@sacundim Consider using the `JUnitQuickcheck` runner that comes with 0.6 alpha builds.
