### ISSUE TITLE
Constrain the length of a generated String via Size annotation

### ISSUE THREAD

**Issue by Bill** [pholser/junit-quickcheck#472]
I saw the answer to https://github.com/pholser/junit-quickcheck/issues/149 but I don't feel like it's a solution to my (simpler) problem. I simply want to generate `String`s with length in a range. It seems obvious to me that the `Size` annotation should operate on `String` parameters.

But something like this:

```java
@RunWith(JUnitQuickcheck.class)
public class QC1 {

  @Property(trials=100, shrink = false)
  public void fooProperty(@Size(min=1, max=2) final String s) {
    assertThat(s.length()).isLessThan(3);
    assertThat(s.length()).isGreaterThan(0);
  }

}
```

results in:

```
None of the candidate generators [com.pholser.junit.quickcheck.generator.java.lang.Encoded, com.pholser.junit.quickcheck.generator.java.lang.StringGenerator] understands all of the configuration annotations [com.pholser.junit.quickcheck.generator.Size]
com.pholser.junit.quickcheck.generator.GeneratorConfigurationException: None of the candidate generators [com.pholser.junit.quickcheck.generator.java.lang.Encoded, com.pholser.junit.quickcheck.generator.java.lang.StringGenerator] understands all of the configuration annotations [com.pholser.junit.quickcheck.generator.Size]
```

Am I not understanding the spirit of QuickCheck? Must I really resort to a custom generator for this?

**Comment by pholser** [comment]
@Bill nah, we can certainly make string generators honor `@Size`.

**Comment by pholser** [comment]
@Bill Let me know how this change suits your needs.

**Comment by pholser** [comment]
Closing, as fix should be on HEAD. Re-open if it doesn't work for you.
