### ISSUE TITLE
repeatable random seeds

### ISSUE THREAD

**Issue by richard-melvin** [pholser/junit-quickcheck#51]
So as far as I can tell, there seems to be no way of forcing junit-quickcheck to always generate repeatable values (which is obviously essential when you want to tie down, investigate and fix some problem found). 

The code below in a generator triggers the assert:
```java
  public T generate(SourceOfRandomness random, GenerationStatus status)
  {
      random.setSeed(22);
      long l1 = random.nextLong();
      random.setSeed(22);
      assert l1 == random.nextLong();
```

This is because ```SourceOfRandomness``` delegates to ```SecureRandom```, which treats a seed as an additional source of randomness, not the whole story.

Ideally, would be able to set the behavior to either deterministic with a known seed, or different each time with an annotation or similar.

**Comment by pholser** [comment]
@richard-melvin Sounds reasonable. How would you imagine triggering the fixed-seed behavior of the randomness passed to a generator for a given theory parameter? Maybe an attribute of `@ForAll`? Another annotation? Should the specific seed be mentioned in such an annotation?

Eager to hear your thoughts.

**Comment by richard-melvin** [comment]
An attribute of ```@ForAll``` would work great I think.

Then you can do
```java
  @Theory
  public void regressionForCaseWhenThingsWentWrongOnce(
      @ForAll(sampleSize = 1, seed=62354276) @From(MyGenerator.class) MyThing thing)
```

If seed not set keep current behavior I guess. 

Maybe also useful to have similar annotations at test class level, e.g.
```java
@ForAllDefaults(sampleSize = 1000, seed=63)
@RunWith(Theories.class)
public class MyTest 
{
```

**Comment by pholser** [comment]
@richard-melvin I'm contemplating how to deliver the seed value. junit-quickcheck works by hooking into JUnit's `ParameterSupplier` feature for theories, so it's difficult to communicate the seed value in an assertion failure/exception. Any thoughts on this? Would it be too presumptive/obtrusive to log a given theory parameter's seed value once before generating values for the parameter?

**Comment by richard-melvin** [comment]
Just logging the seed would be fine as a baseline. 

Maybe could do something clever with a Junit rule, or just have another annotation `@Seed` you can apply to a long in the test class that is read to get initial value, and updated (via reflection, I guess) for each test run.

**Comment by pholser** [comment]
@richard-melvin This is in 0.5 alpha 3. Thanks for the suggestion!
