### ISSUE TITLE
Constrain List argument to non-empty using @SuchThat

### ISSUE THREAD

**Issue by runeflobakk** [pholser/junit-quickcheck#54]
I am using version 0.5-alpha-2, and I am trying to get a non-empty list as a test parameter, like this:

```java
@Theory
public void myTest(@ForAll(sampleSize=8) @SuchThat("not #_.empty") List<Integer> ints) {

}
```

Regardless if I use `not #_.empty` or the opposite, just `#_.empty`, I am not able to get any List which satisfies the OGNL-expression. I have also tried various alternatives using `!` instead of `not`, and ` == false`, but the result is the same. If I remove the `@SuchThat`-annotation, and just print out the lists I get, I see that I get both an empty list, and lists with various random integers. I just want to eliminate the empty one.

### Stacktrace:
```
com.pholser.junit.quickcheck.internal.generator.GenerationContext$DiscardRatioExceededException: For parameter with discard ratio [0], 9 unsuccessful values and 0 successes for a discard ratio of [Infinity]. Stopping.
	at com.pholser.junit.quickcheck.internal.generator.GenerationContext.evaluate(GenerationContext.java:81)
	at com.pholser.junit.quickcheck.internal.generator.GenerationContext.generateUsing(GenerationContext.java:57)
	at com.pholser.junit.quickcheck.internal.generator.GenerationContext.generate(GenerationContext.java:49)
	at com.pholser.junit.quickcheck.internal.generator.RandomTheoryParameterGenerator.generate(RandomTheoryParameterGenerator.java:48)
	at com.pholser.junit.quickcheck.internal.RandomValueSupplier.getValueSources(RandomValueSupplier.java:54)
...
```

### Workaround:
I know I can use `assumeThat`, but I was hoping that by using `@SuchThat` I could prevent the test method to be invoked at all for the empty list case. If the test method is invoked, methods annotated with `@Before` are of course invoked before the test-case is decided to be invalid with `assumeThat`, and my setup code is rather heavy.

**Comment by pholser** [comment]
Will check this out -- thanks!

**Comment by pholser** [comment]
@runeflobakk OK, this is interesting. On every generation, the list generator produces a list of size proportional to a figure that increases with each generation. So initially, you'd get an empty list, then maybe a one-element list, two-element list, and so forth.

In the presence of a `SuchThat` expression, when attempting to generate the next value for a theory parameter, junit-quickcheck will repeatedly generate a value and evaluate the expression against it until the expression evaluates `true`, or until `sampleSize` is hit, or too many values did not cause the expression to evaluate `true`. However, if a generated values doesn't cause the expr to evaluate `true`, the next generation occurs without the "size" figure increasing. So, in your case, an empty list is generated, discarded, then generated again, discarded again...until you hit the discard threshold!

One possible resolution would be to make the figure given by `GenerationStatus.size()` a factor of more than the number of successful evaluations (which in your case ended up being zero always!).

Another potential workaround you could employ would be to supply a generator of Lists that are guaranteed to be non-empty, and mark the appropriate theory parameters with `@From(NonEmpty.class)` (where `NonEmpty` is the name of your list generator).

What do you think about these possibilities?

Thanks again for your interest!

**Comment by tinkerware** [comment]
I think a better resolution is for the generation to guarantee that it will not get stuck due to an arbitrary `@suchThat` constraint. A was bitten by this myself just a couple of weeks ago, my solution was to use a custom generator. Hypothesis is a recent quickcheck-like library for Python and it has a very nice way of value generation and shrinking; maybe that may provide some insights. One that I got was to fuzz the generated list size using geometric distributed random variables. In Java, you can generate a draw a random value with geometric distribution using:

```
    /**
     * Draws one sample between 0 and infinity from a geometric distribution
     * with a mean of `1/p - 1`.
     */
    int sampleGeometricWithP(double p) {
      double denominator = Math.log1p(-p);
      return (int) Math.floor(Math.log(random.getAsDouble()) / denominator);
    }
```

The geometric distribution gives a nicely skewed sample of values where most will be smallish but a small number will be larger, in a non-deterministic way. You can then use the "size" figure to pick the mean of the distribution.

**Comment by tinkerware** [comment]
Here's my utility for creating random samples. Beta distributed samples are for floating point values in the range (0, 1), where most will be below the mean, analogous to the geometrically distributed discrete values.

```
  /**
   * Provides random variables in Beta and Geometric distributions:
   *
   * - The Beta distribution is a special case with alpha at a constant 1;
   * it is analogous to the geometric distribution with X in range of
   * (0, 1).
   *
   * - The geometric distribution allows an optional maximum bound, which
   * we implement by repeatedly sampling until we get a value smaller
   * than the given maximum.
   */
  static class RandomSamples {

    private final DoubleSupplier random;

    RandomSamples(DoubleSupplier random) {
      this.random = random;
    }

    /**
     * Returns `β` given `μ`, where `μ = α / (α + β)`, the expected value of
     * X ∼ Beta(α, β). For the case of `α = 1`, this turns out to be `1/μ - 1`.
     */
    double betaOfMean(double mean) {
      if (!(mean > 0 && mean <= 1)) {
        throw new IllegalArgumentException(String.valueOf(mean));
      }
      return (1d / mean) - 1;
    }

    /**
     * Draws one sample in the open range (0, 1) from a beta distribution
     * with (alpha = 1, beta = beta).
     */
    double sampleBeta(double beta) {
      /*
       * We use a couple of equivalences for the Beta distribution:
       *
       * - If X ∼ Beta(a, b) then 1 - X ∼ Beta(b, a)
       * - If X ∼ U(0, 1) and a > 0 then X^(1/a) ∼ Beta(a, 1)
       *
       * Given these, 1 - X^(1/b) ∼ Beta(1, b) where X ∼ U(0, 1)
       */

      return 1 - Math.pow(random.getAsDouble(), 1d / beta);
    }

    /**
     * Computes `p` from `1/p - 1 = mean`.
     */
    double geometricProbabilityOfMean(double mean) {
      if (Double.compare(mean, 0) <= 0) {
        throw new IllegalArgumentException(String.valueOf(mean));
      }
      return 1 / (1 + mean);
    }

    int sampleGeometricBounded(double mean, int max) {
      return sampleGeometricBoundedWithP(geometricProbabilityOfMean(mean), max);
    }

    int sampleGeometric(double mean) {
      return sampleGeometricWithP(geometricProbabilityOfMean(mean));
    }

    /**
     * Draws one sample between `0` and `max` from a geometric distribution
     * with a mean of `1/p - 1`, discarding any samples greater than or
     * equal to `max`.
     */
    int sampleGeometricBoundedWithP(double p, int max) {
      int result = sampleGeometricWithP(p);
      while (result >= max) {
        result = sampleGeometricWithP(p);
      }

      return result;
    }

    /**
     * Draws one sample between 0 and infinity from a geometric distribution
     * with a mean of `1/p - 1`.
     */
    int sampleGeometricWithP(double p) {
      double denominator = Math.log1p(-p);
      return (int) Math.floor(Math.log(random.getAsDouble()) / denominator);
    }

  }
```

You can create an instance with `new RandomSamples(random::nextDouble)`, where `random` is a `SourceOfRandomness` instance.

**Comment by pholser** [comment]
@tinkerware I agree that it'd be best to have the library avoid getting stuck in the way that bit you and @runeflobakk. Thanks for this insight! Would you be willing to submit a pull request to produce `GenerationContext.size` on each generation in this way?

**Comment by tinkerware** [comment]
I may have some time in the coming week for this; will give it a go.

**Comment by pholser** [comment]
@tinkerware Never mind -- i've gone ahead and incorporated your suggestion. This will be in the forthcoming 0.5 beta 1. Thanks!

**Comment by pholser** [comment]
@runeflobakk Would you mind to have a look at the latest snapshot at oss.sonatype.org? Should hopefully resolve this issue.

**Comment by tinkerware** [comment]
@pholser, thanks for doing that. I was swamped with other work last few weeks. I left a few comments on the commit, hopefully they help. It's great to see this getting better!

**Comment by runeflobakk** [comment]
@pholser thanks, and thanks for chiming in @tinkerware, and sorry for me being missing-in-action. The usual "busy excuse" for my part. I will try the snapshot, at least some time during this weekend, and get back to you. I'm sure it's all fine.

**Comment by runeflobakk** [comment]
Worked like a charm! Did the following steps to verify it:

- found my testcase which originated this issue, test is :white_check_mark:
- removed my workaround described in the OP (`assumeThat(ints, not(empty()))`), test is :x: (as expected)
- added `suchThat="not #_.empty"` to the `@ForAll` annotationt, test is :x:, got the stacktrace as described in the OP (as expected) 
- change to _0.5-alpha-4-SNAPSHOT_, test is :white_check_mark: 

With `sampleSize=5` I now get 5 actual executions of my test, as opposed to just 4 using the `assumeThat`-workaround. The `@Before` setup method also runs as many times as the actual test executions. :+1:

**Comment by tinkerware** [comment]
Latest changes seem great, can't wait to try them out.
