### ISSUE TITLE
Writing a generator using other generators or @ForAll

### ISSUE THREAD

**Issue by Psidium** [pholser/junit-quickcheck#63]
Hi and congrats on the success of your framework.

I'm trying to write a Generator of a Class containing lots of other Classes defined by me.

the way I'm doing is like 
```java
	@Override
	public Guides generate(SourceOfRandomness arg0, GenerationStatus arg1) {
		Guides guide = new Guides();
		guide.setCopyFrom(arg0.nextLong(0, Long.MAX_VALUE));
		guide.setCurrentVersion(arg0.nextLong(0, Long.MAX_VALUE));
		GuideLang guideLang = new GuideLang();
		guideLang.setGuide(guide);
		guideLang.setId(arg0.nextLong(0, Long.MAX_VALUE));
		guideLang.setLang(Languages.pt_BR);  //Enum???
                guide.setLang(guideLangs);
                return guide;
```

is there a way to use @ForAll inside a Generator, like, in the Enum? 

Thanks,
Psidium

**Comment by pholser** [comment]
@Psidium Thanks for your interest in junit-quickcheck!

At present, generating an object graph using a custom generator is a bit clunky.

If instances of your class can be fully realized using one of its constructors, I would recommend the `Ctor` generator. For example, assuming classes Foo, Bar, and Baz, and generators made available via `ServiceLoader` for each:

    public class Foo {
        public Foo(Bar bar, Baz baz) { /* ... */ }
    }

    @Theory public void holds(@ForAll @From(Ctor.class) Foo f) {
        // ...
    }

Similarly, there is the `Fields` generator (though mostly intended for one-off "tuple" classes with `public` fields).

If you have custom generators for all members of the object graph, the generators could be composed:

    @Override public Guides generate(...) {
        Guides g = new Guides();
        g.setCopyFrom(...);
        g.setCurrentVersion(...);
        GuideLang lang = guideLangGenerator.generate(...);
        lang.setGuide(g);
        // ...
    }

If you are asking about choosing a random `enum` value, you could do what the internal `EnumGenerator` does and choose a random element from the enum's `getEnumConstants()` array. Maybe it'd be nice to add to `SourceOfRandomness` a method for choosing array/collection elements at random? Maybe also a `nextEnum` method?

    class SourceOfRandomness {
        // ...
       <T extends Enum<T>> T nextEnum(Class<T> clazz) {
          // ...
       }
    }

Let me know whether this makes sense, and what if anything we might do to consider the issue resolved.

Thanks again!

**Comment by pholser** [comment]
Another possibility might be to create a peer of `Ctor` and `Fields` called `Mutators`, that would work like `Ctor` but then attempt to call mutator methods on the random instance with random data appropriate for the type.

Yet another possibility would be to expose to a `Generator` a way to ask for a `Generator` compatible with a specific type, for the `Generator` to use while generating neighbors in the object graph.

**Comment by pholser** [comment]
@Psidium Have a look at the `gen()` functionality on master (post-0.6) -- does this help in creating generators of composed objects? What does it get right? What could it do better?

Thanks!

**Comment by Psidium** [comment]
Hi! and wow! you're implementing it!

Unfortunately the project I was working on using quick check has been cut out :cry:
I'll try to find the source code for my former project and test this new functionality whenever I find the time, 
thanks so much :smile:

**Comment by pholser** [comment]
@Psidium Thanks! For now, I will consider the matter closed. If you have any other suggestions, or trip over a bug, please let me know.
