### ISSUE TITLE
Where is 0.6-alpha-1?

### ISSUE THREAD

**Issue by jbrains** [pholser/junit-quickcheck#67]
The README says "0.6-alpha-1", a version which appears not to exist at https://repo1.maven.org/maven2/com/pholser/junit-quickcheck-core/ as of the instant I write this.

**Comment by pholser** [comment]
@jbrains Whoops. Was sitting in a Sonatype staging repo, unreleased.

Should be available in Maven central soon.

**Comment by jbrains** [comment]
Thank you! It happens.

-- 
J. B. Rainsberger :: @jbrains :: online-training.jbrains.ca :: blog.thecodewhisperer.com :: jbrains.ca
