### ISSUE TITLE
Generators for java.time.* classes

### ISSUE THREAD

**Issue by pholser** [pholser/junit-quickcheck#71]

**Comment by ivern** [comment]
I've got some work in progress here, should be finished sometime next week depending on free time:
https://github.com/ivern/junit-quickcheck/tree/java-time-generators

**Comment by ivern** [comment]
I'd like your thoughts on how to implement a generator for java.time.Period.  The problem with periods is that days can't be normalized--periods don't keep track of beginning or end date, so the number of actual days in the month can't be properly generated in a way consistent with what one would expect if the Period was initially created from a date range.

I think the relatively naive approach of generating Periods as if all months had 31 days (ie, projecting Periods onto the integer line as (Y * 12 + M) * 31 + D and generating a long is good enough.  Thoughts?

**Comment by ivern** [comment]
Separate question: when I finish, do you want me to rebase all my commits into a single clean commit for all the java.time.* work, or keep history as-is?

**Comment by pholser** [comment]
I'd say leave the commits separate. Thanks again!

**Comment by ivern** [comment]
No problem--still three classes to implement (haven't had much time this past week) and then some cleanup and review to make sure I didn't miss anything.
