### ISSUE TITLE
Add shrinking control "maxTime"

### ISSUE THREAD

**Issue by pholser** [pholser/junit-quickcheck#75]
Stop the shrinking process after `maxTime` seconds have elapsed.

Should this override the `maxShrinks` and `maxShrinkDepth` or not?

**Comment by ivern** [comment]
I think it should override either--the primary use case I see for something like maxTime is as a cap on resource utilization.

**Comment by pholser** [comment]
@ivern By all means, go for it! Thanks for your help!
