### ISSUE TITLE
GeneratorConfiguration fails in Kotlin

### ISSUE THREAD

**Issue by dmcg** [pholser/junit-quickcheck#77]
OK, bit of an edge case I admit, but I notice that @InRange doesn't work in Kotlin. I believe it is because the Kotlin compiler doesn't support ElementType.TYPE_USE, so that Parameter.getAnnotatedType().getAnnotations() returns an empty array.

TBH I don't grok the significance of TYPE_USE. I'm happy to help if I can - I have a failing Kotlin test case and a passing Java one.

**Comment by pholser** [comment]
`ElementType.TYPE_USE` is to enable the annotation on constructs like `List<@InRange(...) Integer>`:

    http://pholser.github.io/junit-quickcheck/site/0.6-alpha-3-SNAPSHOT/usage/configuring.html

In my opinion, having junit-quickcheck honor configuration annotations on type uses is a nice touch. That, coupled with junit-quickcheck's unabashed JDK >= 8-only mindset, makes me reluctant to undo the additions of `ElementType.TYPE_USE` on junit-quickcheck's supplied configuration annotations.

**Comment by dmcg** [comment]
That's cool -  I'm learning there are unsung additions to Java 8!

If you were to fetch the annotations directly through parameter.getAnnotations() as well as getAnnotatedType().getAnnotations() it would find those added by the Kotlin compiler. Of course you'd then have the problem of how to merge them - is that conceptually hard?

**Comment by pniederw** [comment]
Same problem for `@ValuesOf`.

> If you were to fetch the annotations directly through parameter.getAnnotations() as well as getAnnotatedType().getAnnotations() it would find those added by the Kotlin compiler.

+1

**Comment by pholser** [comment]
@dmcg @pniederw Thanks for the info! This'll be interesting to dive into Kotlin a bit.

**Comment by pholser** [comment]
@dmcg @pniederw Let me make sure I'm understanding the problem correctly. Is it the case that the Kotlin compiler creates class files such that annotations such as `@InRange` and `@ValuesOf` on a method parameter are available via `parameter.getAnnotations()` but not via `parameter.getAnnotatedType().getAnnotations()`?

If so, I suspect that we could ask for both sets of annotations on creation of a `ParameterTypeContext` and union the sets.

**Comment by pniederw** [comment]
> Is it the case that the Kotlin compiler creates class files such that annotations such as @InRange and @ValuesOf on a method parameter are available via parameter.getAnnotations() but not via parameter.getAnnotatedType().getAnnotations()?

That's what I've been seeing in my experiments.

> If so, I suspect that we could ask for both sets of annotations on creation of a ParameterTypeContext and union the sets.

Happy to give it a try.

**Comment by dmcg** [comment]
I concur.

Thanks for working on this - I want to play with shrinking!

**Comment by pholser** [comment]
@dmcg @pniederw Give latest 0.6 alpha 3 snapshot at oss.sonatype.org a spin, and let me know if this works any better for you. My admittedly cursory Kotlin tests seemed to honor the config annotations.

**Comment by dmcg** [comment]
Couldn't find snapshot on sonatype, but building from source gives expected behaviour for `@InRange` in Kotlin. Thanks!
