### ISSUE TITLE
Support mixing @Test and @Property methods in same class

### ISSUE THREAD

**Issue by pniederw** [pholser/junit-quickcheck#80]
It would be handy if `@Property` methods could be added to a standard JUnit test class.

**Comment by pholser** [comment]
Running `@Test` methods on a class that is `@RunWith(JUnitQuickcheck.class)` shouldn't be much trouble. I'll see about adding that.

Thanks for your interest!

**Comment by pholser** [comment]
Latest 0.6 alpha 3 snapshot on oss.sonatype.org should have this. Thanks again!

**Comment by pniederw** [comment]
Thanks for the feature!
