### ISSUE TITLE
Methods with @ValuesOf parameters should have all combinations of parameter values checked

### ISSUE THREAD

**Issue by pniederw** [pholser/junit-quickcheck#81]
```java
class MyEnum { ONE, TWO }
...
@Property
public void test(@ValuesOf MyEnum myEnum, @ValuesOf boolean bool) {}
```

Currently this will run 100 iterations, half of which will use `(ONE, false)`, and the other half `(TWO, true)`. I think it would be better to run 4 iterations: `(ONE, false)`, `(ONE, true)`, `(TWO, false)`, `(TWO, true)`.

If more parameters are added (say `int x`), it would still be useful to cycle through all combinations of `myEnum` and `bool`, rather than alternating between `(ONE, false)` and `(TWO, true)`.

**Comment by pholser** [comment]
Agreed.

**Comment by pniederw** [comment]
I feel that unifying the two approaches could be worthwhile: be exhaustive where feasible, and choose an "interesting" set of samples otherwise. As I see it, the only motivation for sampling is that being exhaustive is often too expensive (or impossible), so why not be exhaustive where it's cheap.

**Comment by pholser** [comment]
@pniederw That sounds reasonable. I'd need to work out who wins in a fight between `Property.trials` and differently-limited property parameters, but I think it's worth exploring further.

Re: "interesting" samples: the integral generators in `junit-quickcheck-generators` currently lean on `java.util.Random.nextLong()`. Certainly other strategies are possible; in particular, we might choose to generate as a function of `GenerationStatus.size` like the collection/map/array generators do. Shrinking of failures is done by mimicking what Haskell's QuickCheck does.

**Comment by pholser** [comment]
@pniederw I am leaning toward offering "modes" for `@Property` methods to be tested in:

    enum Mode { TUPLES, PERMUTATIONS };

    @interface Property {
        // ...

        Mode mode() default TUPLES;
    }

    @Property(mode = PERMUTATIONS)
    public void prop(int arg0, boolean arg1, Mode mode) {
        /*
        Invoked min(|int|, trials) * min(|boolean|, trials) * min(|Mode|, trials)
        times --> 100 * 2 * 2
        */
    }

In `PERMUTATIONS

**Comment by pholser** [comment]
@pniederw Re: the above: in short, I'm proposing to:

1. Deprecate `@ValuesOf`
2. Create another issue to track development of permutations/tuples mode of property verification
3. Close this request.

**Comment by tinkerware** [comment]
How about `EXHAUSTIVE` and `SAMPLING` as mode names? I find `TUPLES` and `PERMUTATIONS` too generic; they would make me look up the meaning every time I use them.

How would `@Only` work against any method parameter when it can only accept `String`-typed values? I liked `@ValuesOf` because it provides a simple way to enumerate `boolean`'s and `Enum`'s. 

I agree with @pniederw that there is value in letting the test choose which parameters to consider exhaustive and sample the rest. I also like the way you outlined how `trials` and exhaustive parameters work.

**Comment by pholser** [comment]
@tinkerware I like `EXHAUSTIVE` and `SAMPLING` much better. Thanks for the suggestion!

Re: `@Only` -- I'm thinking that if the target type has an accessible one-arg `String` ctor or an accessible static `valueOf(String)` method, we'd use one of those to convert the values of `@Only`. That would take care of the primitives, their wrappers, and `enum`s at least. Could allow specification of the class of a converter, like say `@Only({"01/02/2016"}, by = MMDDYYYY.class)`.

So, my current thinking:

Admit a `mode` attribute on `Property`:

```java
enum Mode { SAMPLING, EXHAUSTIVE }

@interface Property {
    // ...

    Mode mode default SAMPLING;
}

enum Response { YES, NO, UNSURE }

@Property(trials = 45) public void sampling(
    int arg0,
    boolean arg1,
    Response arg2,
    @Only({"1", "2", "0", "-1"}) int arg3) {

    /*
    Invoked 45 times.
    45 tuples (arg0, arg1, arg2, arg3) generated.
    Each value of each tuple chosen at random from its domain.
    Domain of arg3 narrowed by @Only.
    */
}

@Property(trials = 77, mode = EXHAUSTIVE) public void sampling(
    int arg0,
    boolean arg1,
    Response arg2,
    @Only({"1", "2", "0", "-1"}) int arg3) {

    /*
    Invoked 77 * 2 * 3 * 4 times --
    once for each choice of 77 randomly chosen arg0,
    two possible values of arg1, three possible values of arg2,
    and four possible values of arg2.
    */
}
```

I'm thinking that with such a scheme, the utility of `@ValuesOf` diminishes. in `EXHAUSTIVE` mode, you're guaranteed that every possible `boolean` and `enum` value gets tried. In `SAMPLING` mode, leaving `@ValuesOf` doesn't help much -- every tuple gets the next value in the cycle, but you're not restricting the number of trials, you're still getting `trials` tuples, not min[k] { min( |arg_k|, trials) }.

**Comment by tinkerware** [comment]
This looks really good! I agree `ValuesOf` loses its current appeal with this scheme.

**Comment by pholser** [comment]
Fair enough. I'm going to close this, and create another issue to track the development of the new property verification "mode".
