### ISSUE TITLE
Optional hook for processing counter examples

### ISSUE THREAD

**Issue by philipp-classen** [pholser/junit-quickcheck#84]
Right now, once a counter example for a property is found, it will only be available to the user as a string representation. For simple data like numbers that is fine, but for more complex data, I would find it useful to have access to the object itself.

One way to provide the option would be to provide a hook that is called with the counter example. By default, it is a no-op, so it adds no complexity to users that do not need it.

Possible use cases for the hook:
- serialize the object in a application specific format, so it can be easily reproduced later or used as a regression test case
-  having a convenient way to debug into the problem

This two cases are difficult to achieve by just having the string representation.

I thought about implementing a patch to sketch the idea but I wanted to ask first whether there is already a good way to achieve it? If not, do you see value in adding such a feature?

**Comment by pholser** [comment]
@philipp-classen Thanks for your interest! This sounds useful indeed. I'd be very interested to see your patch.

**Comment by philipp-classen** [comment]
Please have a look at pull request #88

**Comment by pholser** [comment]
Merged. I renamed the hook class, but otherwise very little change.

Thanks for your contribution!
