### ISSUE TITLE
Enrich SourceOfRandomness 

### ISSUE THREAD

**Issue by nirfeldman** [pholser/junit-quickcheck#85]
You can add to the SourceOfRandomness some methods that are heavily used:
nextPositiveInt / nextPositiveLong .... - This is useful for IDs.

**Comment by pholser** [comment]
@nirfeldman Thanks for your interest in junit-quickcheck!

I'm not sure I want to fatten the API of `SourceOfRandomness` with these methods. IMO `nextInt(1, max)` and `nextLong(1, max)` should suffice. When in doubt, leave it out.
