### ISSUE TITLE
Defining specific values that are always generated

### ISSUE THREAD

**Issue by emccorson** [pholser/junit-quickcheck#86]
It would be great if there was a way to give a generator a specific set of values that are always generated before the random values, because the randomly generated values often don't include important values (e.g. edge cases).

**Comment by pholser** [comment]
@emccorson Thanks for your interest! That sounds useful. I'm wondering how that might look from the caller's perspective?

**Comment by emccorson** [comment]
How about something like:
```java
@Property public void someIntThing(@AlwaysUse({0,1,2,4}) int x)
```
I'm not overly familiar with annotations but I think that syntax is ok.

**Comment by pholser** [comment]
@emccorson Something alone those lines sounds right.

Note that this annotation would be limited to [types that an annotation's values can have](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1) -- unless we want to get into converting `String` values to the target type according to some rules or conventions.

**Comment by pholser** [comment]
@emccorson After mulling this over for a (longer than I had hoped) while, I think I'm going to leave this feature out.

In my mind, QuickCheck implementations are all about discovering unusual failure conditions via random testing. Tacking on a bit to "always try these values", in my mind, makes for a less coherent product.

I know that JUnit's Theories machinery supports what you're looking for in the form of `DataPoint`s. Another option might be, if you have a property method, to have another test that calls the property method with the values you want to try:

    @RunWith(JUnitQuickcheck.class)
    public class IntegerProperties {
        @Property public void absForPositives(int i) {
            assumeThat(i, greaterThan(0));
            assertEquals(i, Math.abs(i));
        }

        @Property public void absForNegatives(int i) {
            assumeThat(i, lessThan(0));
            assertEquals(-i, Math.abs(i));
        }

        @Test public void absForInterestingPositives() {
            asList(1, 2, 3, 5, 8).forEach(this::absForPositives);
        }

        @Test public void absForInterestingNegatives() {
            asList(-1, -2, -4, -7).forEach(this::absForNegatives);
        }
    }

**Comment by pholser** [comment]
Though I'm closing this issue, I should mention that there will be a future feature whereby you can mark a property parameter as `@Only({ value, ..., value })`. In the new ("sampling") mode, each value for that parameter will be chosen at random from the specified set, with (roughly) equal probability. In old, Theories-style "exhaustive" mode, you'll get very combination of theory parameters, and each value specified will be mixed in.
