### ISSUE TITLE
Generate objects from a package that are subclass of some class

### ISSUE THREAD

**Issue by octopuscabbage** [pholser/junit-quickcheck#90]
I have a bunch of objects in a package which I would like to generate that all implement the same interface. I would like to be able to generate an instance of any of these objects by specifiying the interface, the package, and optionally the generator to generate the instances.

**Comment by octopuscabbage** [comment]
If I recall correctly Haskell allows generating random instances of a typeclass so it would probably look similar. This stackoverflow question might also be helpful:

http://stackoverflow.com/questions/520328/can-you-find-all-classes-in-a-package-using-reflection

**Comment by pholser** [comment]
@octopuscabbage Thanks for your interest in junit-quickcheck!

Supposing your interface is `Foo`, with concrete implementers `Bar`, `Baz`, and `Quux`: if you have generators `BarMaker`, `BazMaker`, and `QuuxMaker` available via `ServiceLoader` for `Bar`, `Baz`, and `Quux`, then a property parameter of type `Foo` should "just work":

    @Property public void aFooProperty(Foo f) {
    }

If you didn't want to make the generators available via `ServiceLoader`, you can name them explicitly via `@From`:

    @Property public void aFooProperty(
        @From(BarMaker.class)
        @From(BazMaker.class)
        @From(QuuxMaker.class)
        Foo f) {

        // ...
    }

Also, if `Foo` were a functional interface, and your property parameter is of type `Foo`, junit-quickcheck would generate random instances of `Foo` (via dynamic proxies) for you.

Will this suffice? Maybe I'm missing something?

Would it help to have junit-quickcheck attempt to generate random instances of interfaces that aren't functional interfaces?

**Comment by octopuscabbage** [comment]
Thanks for your help. Most of my problem is wanting to use the @Fields generator with the concrete implemenation

> Would it help to have junit-quickcheck attempt to generate random instances of interfaces that aren't functional interfaces?

Yeah that would be basically what I would like. It seems like it could be useful.

**Comment by pholser** [comment]
@octopuscabbage OK - I think I'm getting you.

Certainly generator `Fields` will work on concrete classes:

    @Property public void bars(@From(Fields.class) Bar b) {
        // ...
    }

Once we're past 0.6, I'm going to add something to allow a generator writer to do something like:

    public class BarByFieldsMaker extends Generator<Bar> {
        @Override public Bar generate(random, status) {
            return gen().fieldsOf(Bar.class).generate(random, status);
        }
    }

Then having N of these for your N interface implementers...

I think maybe you're looking for something like:

    @Property public void aFooProperty(
        @From(Fields.class, Bar.class)
        @From(Fields.class, Baz.class)
        @From(Fields.class, Quux.class)
        Foo f) {

        // ...
    }

Or, maybe even better:

    @Property public void aFooProperty(
        @FieldsOf(Bar.class)
        @FieldsOf(Baz.class)
        @FieldsOf(Quux.class)
        Foo f) {

       // ...
    }

Where `@FieldsOf(X.class)` functions like `@From(Fields.class) does on a property parameter of type `X`?

**Comment by octopuscabbage** [comment]
Nope, from a cursory glance it looks great

**Comment by pholser** [comment]
Right on. Thanks!
