### ISSUE TITLE
Report seed in test runner for failed tests

### ISSUE THREAD

**Issue by spodkowinski** [pholser/junit-quickcheck#92]
Re-running a failed test requires to retrieve the seed from the log file as [described in the documentation](https://pholser.github.io/junit-quickcheck/site/0.6-beta-1/usage/seed.html). It would be much more convenient to have the seed reported by the test runner (`PropertyStatement.evaluate()`) instead.
I also wonder if it wouldn't be easier to use a single seed for all parameters.

**Comment by pholser** [comment]
@spodkowinski Thanks for your interest in junit-quickcheck!

I will try to think of a way to report seeds on failures in a way other than logging them. I didn't want to wrap all potential exceptions raised by the property in an exception that captures the seed...not sure how else we might report the seeds. Any ideas?

**Comment by spodkowinski** [comment]
I think I already have a good solution that would also address some other aspects. I'll get back with a PR soon!

**Comment by pholser** [comment]
Excellent -- looking forward to seeing your work!
